import { BaseAgent } from './BaseAgent';
import { AgentResult, GeneratedFile } from '../utils/types';
import { SharedMemory } from '../utils/SharedMemory';
import { SimpleLogger } from '../utils/SimpleLogger';
import { AICodeGenerator } from '../services/AICodeGenerator';

interface StyleConfig {
  theme: {
    colors: Record<string, string>;
    fonts: Record<string, string>;
    spacing: Record<string, string>;
  };
  tailwindClasses: Record<string, string[]>;
  customCSS: string;
}

interface StyleTask {
  prompt: string;
  sharedMemory: SharedMemory;
}

export class StyleGeneratorAgent extends BaseAgent {
  private readonly aiGenerator = new AICodeGenerator();

  constructor() {
    super('style-generator');
  }

  protected async setup(): Promise<void> {
    // No additional setup needed
  }

  async executeTask(task: StyleTask | string): Promise<AgentResult> {
    const prompt = typeof task === 'string' ? task : task.prompt;
    const sharedMemory = typeof task === 'string' ? new SharedMemory('styles') : task.sharedMemory;

    const requirements = sharedMemory.get('requirements');
    const architecture = sharedMemory.get('architecture');

    this.logger.info('Generating style configuration');
    const start = Date.now();

    try {
      const stylePrompt = this.buildPrompt(prompt, requirements, architecture);
      const response = await this.aiGenerator.generateComponent({
        prompt: stylePrompt,
        componentName: 'StyleConfig',
        features: [],
      });

      const styleConfig = this.parseStyles(response.code ?? '{}');
      const files = this.buildStyleFiles(styleConfig);

      sharedMemory.set('styles', styleConfig);

      return {
        success: true,
        files,
        metadata: {
          executionTime: Date.now() - start,
          resourceUsage: {
            memory: process.memoryUsage().heapUsed / 1024 / 1024,
            cpu: 0,
          },
        },
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.logger.error('Style generation failed', error as Error);
      return {
        success: false,
        errors: [message],
      };
    }
  }

  private buildPrompt(prompt: string, requirements: any, architecture: any): string {
    return `You are a UI designer specializing in Tailwind CSS. Create a cohesive design system.

USER_PROMPT:
${prompt}

REQUIREMENTS:
${JSON.stringify(requirements, null, 2)}

ARCHITECTURE:
${JSON.stringify(architecture, null, 2)}

Return ONLY valid JSON:
{
  "theme": {
    "colors": Record<string, string>,
    "fonts": Record<string, string>,
    "spacing": Record<string, string>
  },
  "tailwindClasses": Record<string, string[]>,
  "customCSS": string
}`;
  }

  private parseStyles(payload: string): StyleConfig {
    const cleaned = payload.replace(/```json\s*/g, '').replace(/```/g, '').trim();
    try {
      const parsed = JSON.parse(cleaned);
      return {
        theme: parsed.theme ?? {
          colors: { primary: '#2563eb' },
          fonts: { sans: 'Inter, system-ui, sans-serif' },
          spacing: { md: '1rem' },
        },
        tailwindClasses: parsed.tailwindClasses ?? {},
        customCSS: parsed.customCSS ?? '',
      };
    } catch (error) {
      this.logger.error('Failed to parse style JSON', error as Error);
      return {
        theme: {
          colors: { primary: '#2563eb', secondary: '#1e293b' },
          fonts: { sans: 'Inter, system-ui, sans-serif' },
          spacing: { sm: '0.5rem', md: '1rem', lg: '2rem' },
        },
        tailwindClasses: {},
        customCSS: '',
      };
    }
  }

  private buildStyleFiles(config: StyleConfig): GeneratedFile[] {
    const tailwindContent = `import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: ${JSON.stringify(config.theme.colors ?? {}, null, 2)},
      fontFamily: ${JSON.stringify(config.theme.fonts ?? {}, null, 2)},
      spacing: ${JSON.stringify(config.theme.spacing ?? {}, null, 2)},
    },
  },
  plugins: [],
} satisfies Config
`;

    const customCss = config.customCSS?.trim() ||
      `/* Custom styles generated by StyleGeneratorAgent */
.glass-panel {
  backdrop-filter: blur(12px);
}
`;

    return [
      {
        path: 'tailwind.config.ts',
        content: tailwindContent,
      },
      {
        path: 'src/styles/custom.css',
        content: customCss,
      },
    ];
  }
}


