import Anthropic from '@anthropic-ai/sdk';
import { Logger } from '../utils/Logger';
import { RateLimiter } from '../utils/RateLimiter';
import { multiModelAI, AIRequest } from './MultiModelAIService';

export interface AIGenerationRequest {
  prompt: string;
  componentName: string;
  features: string[];
  styling?: {
    animations: boolean;
    theme: string;
  };
  context?: string;
  modelPreference?: 'speed' | 'quality' | 'cost';
  provider?: 'anthropic' | 'openai' | 'gemini' | 'auto';
}

export interface AIGenerationResponse {
  success: boolean;
  code?: string; // Main component code (for backwards compatibility)
  files?: { path: string; content: string }[]; // Multi-file support
  dependencies: string[];
  error?: string;
  warning?: string; // For non-fatal issues like parsing fallbacks
  parseWarning?: string; // Specific warning about file parsing
  metadata?: {
    provider: string;
    model: string;
    responseTime: number;
    tokens: number;
    cost: number;
    parsingMethod?: 'json' | 'markdown' | 'fallback';
  };
}

export class AICodeGenerator {
  private anthropic: Anthropic;
  private logger: Logger;
  private limiter: RateLimiter;

  constructor() {
    this.anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
    this.logger = new Logger(process.cwd());
    this.logger.initialize().catch(console.error);
    this.limiter = new RateLimiter(5);
  }

  async generateComponent(request: AIGenerationRequest): Promise<AIGenerationResponse> {
    try {
      console.log('🎨 AICodeGenerator: Starting component generation');
      console.log('📝 AICodeGenerator: Request:', {
        componentName: request.componentName,
        features: request.features,
        promptLength: request.prompt.length
      });

      this.logger.info('AICodeGenerator', 'Generating component with multi-model AI', {
        componentName: request.componentName,
        features: request.features,
        provider: request.provider || 'auto',
        preference: request.modelPreference || 'quality',
      });

      console.log('🏗️ AICodeGenerator: Building prompts');
      const systemPrompt = this.buildSystemPromptMultiFile(request);
      const userPrompt = this.buildUserPromptMultiFile(request);
      console.log('📊 AICodeGenerator: Prompt sizes:', {
        system: systemPrompt.length,
        user: userPrompt.length
      });

      // Use multi-model AI service
      const aiRequest: AIRequest = {
        prompt: userPrompt,
        systemPrompt,
        maxTokens: 8000,
        temperature: 0.7,
        useCase: 'code_generation',
        priority: request.modelPreference || 'quality'
      };

      console.log('🤖 AICodeGenerator: Calling multiModelAI.generate()...');
      const startTime = Date.now();
      const response = await multiModelAI.generate(aiRequest);
      const elapsed = Date.now() - startTime;
      console.log(`✅ AICodeGenerator: multiModelAI.generate() completed in ${elapsed}ms`);

      if (!response.content) {
        throw new Error('No code generated by AI');
      }

      // Parse the multi-file JSON response
      const parseResult = this.parseMultiFileResponse(response.content);

      if (parseResult.files.length === 0) {
        throw new Error('AI generated no files');
      }

      // Extract all dependencies from all files
      const dependencies = this.extractDependenciesFromFiles(parseResult.files);

      this.logger.info('AICodeGenerator', 'Multi-file component generated successfully', {
        filesCount: parseResult.files.length,
        dependencies,
        provider: response.provider,
        model: response.model,
        responseTime: response.responseTime,
        cost: response.usage.cost,
        parsingMethod: parseResult.method,
      });

      // Ensure all required configuration files are present
      const completeFiles = this.ensureRequiredFiles(parseResult.files, dependencies, request.componentName);

      const result: AIGenerationResponse = {
        success: true,
        files: completeFiles,
        code: completeFiles.find(f => f.path === 'src/App.tsx')?.content || '', // Backwards compatibility
        dependencies,
        metadata: {
          provider: response.provider,
          model: response.model,
          responseTime: response.responseTime,
          tokens: response.usage.totalTokens,
          cost: response.usage.cost,
          parsingMethod: parseResult.method,
        },
      };

      // Add warning if fallback parsing was used
      if (parseResult.warning) {
        result.parseWarning = parseResult.warning;
        result.warning = parseResult.warning;
      }

      return result;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      this.logger.error('AICodeGenerator', 'Failed to generate component', {
        error: errorMessage,
      });

      return {
        success: false,
        code: '',
        files: [],
        dependencies: [],
        error: errorMessage,
      };
    }
  }

  private buildSystemPrompt(request: AIGenerationRequest): string {
    return `You are an expert React developer specializing in creating modern, functional web applications.

Your task is to generate a complete, working React component based on the user's requirements.

CRITICAL REQUIREMENTS:
- Use React 18+ with TypeScript
- Use modern React patterns (hooks, functional components)
- Include proper TypeScript types and interfaces
- Use Tailwind CSS for styling (with inline classes, use modern gradients and shadows)
- Make the component fully functional and interactive with realistic data
- Include proper error handling and loading states
- Use semantic HTML elements
- Make it responsive and accessible (works on mobile, tablet, desktop)
- Add smooth transitions and professional UI/UX
- Include keyboard navigation and ARIA labels
- Use modern design patterns (cards, modals, toasts, etc.)
- Add data persistence with localStorage where appropriate

🚨 CRITICAL - SINGLE FILE COMPONENT RULE 🚨
This is the MOST IMPORTANT requirement - if you violate this, the app will BREAK:

❌ ABSOLUTELY FORBIDDEN - You MUST NOT do these:
- NO "import ... from './components/...'"
- NO "import ... from './utils/...'"
- NO "import ... from './hooks/...'"
- NO "import ... from './types/...'"
- NO "import ... from './lib/...'"
- NO "import ... from './services/...'"
- NO relative imports starting with "./" or "../"

✅ ALLOWED - You CAN ONLY import from:
- "react" and "react-dom"
- npm packages: "framer-motion", "lucide-react", "clsx", "date-fns", etc.

✅ REQUIRED - Put EVERYTHING in ONE file:
- Define ALL interfaces and types at the top of the file
- Define ALL helper functions in the file
- Define ALL sub-components in the file (before the main component)
- Define ALL utilities in the file
- Define ALL constants in the file
- The ONLY exports should be: "export default function App()"

Example CORRECT structure:
\`\`\`typescript
import React, { useState } from 'react';

// Types
interface Recipe {
  id: number;
  title: string;
}

// Helper functions
const formatDate = (date: Date) => date.toLocaleDateString();

// Sub-components (if needed)
const RecipeCard = ({ recipe }: { recipe: Recipe }) => (
  <div>{recipe.title}</div>
);

// Main component - MUST be named "App"
export default function App() {
  return <div>...</div>;
}
\`\`\`

COMPONENT SPECIFICATIONS:
- Component Name: App (always use "App" as the exported component name)
- Features: ${request.features.join(', ')}
- Theme: ${request.styling?.theme || 'light'}
- Animations: ${request.styling?.animations ? 'Include smooth animations' : 'No animations needed'}

OUTPUT FORMAT:
Return ONLY the complete React component code. Do not include markdown code fences (\`\`\`), explanations, or any other text. Just the raw TypeScript/React code.

The component should be a complete, functional implementation in ONE SINGLE FILE.`;
  }

  private buildUserPrompt(request: AIGenerationRequest): string {
    let prompt = `Create a React component with the following requirements:\n\n`;

    prompt += `DESCRIPTION: ${request.prompt}\n\n`;

    if (request.features.length > 0) {
      prompt += `REQUIRED FEATURES:\n`;
      request.features.forEach(feature => {
        prompt += `- ${feature}\n`;
      });
      prompt += '\n';
    }

    if (request.context) {
      prompt += `ADDITIONAL CONTEXT: ${request.context}\n\n`;
    }

    prompt += `CRITICAL REMINDERS:
- Create a SINGLE, SELF-CONTAINED file
- NO local imports (no "./components/...", no "./utils/...", etc.)
- Put ALL types, sub-components, and helpers IN THE SAME FILE
- Export the main component as: "export default function App()"
- Make it fully functional and production-ready`;

    return prompt;
  }

  private buildSystemPromptMultiFile(request: AIGenerationRequest): string {
    return `# Role
You are an expert React TypeScript developer specializing in creating modern, production-ready web applications.

# Core Principles
**EFFICIENCY FIRST**: Generate ONLY what's necessary. Don't over-engineer or add features not requested.
**QUALITY OVER QUANTITY**: Focus on making the code production-ready, not feature-rich.
**RESPECT CONSTRAINTS**: Work within the given requirements without adding "nice to have" features.

# Your Expertise
- Building scalable React applications with TypeScript
- Creating intuitive user interfaces with modern design patterns
- Implementing efficient state management and data flow
- Writing clean, maintainable, and performant code
- Following React best practices and accessibility standards

# Primary Task
Generate a COMPLETE, MULTI-FILE React TypeScript application based STRICTLY on the user's requirements.
- ✅ DO: Include everything needed to run the app
- ✅ DO: Follow best practices and write production-ready code
- ❌ DON'T: Add extra features not requested
- ❌ DON'T: Over-engineer simple requirements
- ❌ DON'T: Include unnecessary complexity

## Technical Specifications
- **Framework**: React 18+ with TypeScript
- **Styling**: Tailwind CSS with custom design system
- **State**: Modern React patterns (hooks, context when needed)
- **Quality**: Production-ready with error handling
- **Accessibility**: WCAG 2.1 AA compliant
- **Performance**: Optimized for fast loading and smooth interactions

# Architecture Requirements

## Required File Structure
You MUST generate ALL necessary files in this structure:

### Core Application
- \`src/App.tsx\` - Main application component with routing and global state
- \`src/main.tsx\` - React 18 entry point with createRoot
- \`src/index.css\` - Global styles and Tailwind configuration

### Component Architecture
- \`src/components/*.tsx\` - UI components (one per file, properly typed)
- \`src/layouts/*.tsx\` - Layout components if needed
- \`src/pages/*.tsx\` - Page components for different routes

### Type Safety & Utils
- \`src/types/index.ts\` - All TypeScript interfaces and types
- \`src/utils/*.ts\` - Pure utility functions and helpers
- \`src/hooks/*.ts\` - Custom React hooks for logic reuse

### Configuration Files
- \`package.json\` - Complete dependency list and scripts
- \`tsconfig.json\` - TypeScript configuration
- \`tailwind.config.js\` - Tailwind CSS configuration
- \`index.html\` - HTML entry point

# Code Quality Standards

## React Best Practices
- Use functional components with proper TypeScript typing
- Implement proper error boundaries and loading states
- Follow React naming conventions (PascalCase for components)
- Use semantic HTML elements for accessibility
- Implement proper form validation and error handling

## TypeScript Excellence
- Define comprehensive interfaces for all data structures
- Use proper generic types where applicable
- Implement strict null checks and proper error types
- Export types for reusability across components

## UI/UX Standards
- Create responsive layouts that work on all devices
- Implement smooth transitions and micro-interactions
- Use consistent spacing, typography, and color schemes
- Ensure keyboard navigation and screen reader support
- Follow modern design patterns (cards, buttons, forms)

# Component Specifications
- **Component Name**: ${request.componentName}
- **Required Features**: ${request.features.join(', ')}
- **Theme**: ${request.styling?.theme || 'light'} mode with proper contrast
- **Animations**: ${request.styling?.animations ? 'Smooth animations with framer-motion' : 'Subtle CSS transitions'}
- **Styling Approach**: Tailwind CSS with custom design tokens

# Critical Output Requirements

## Format: JSON Array Only
You MUST return ONLY a JSON array. No markdown, no explanations, no code blocks.

## Required Structure

[
  {
    "path": "src/App.tsx",
    "content": "import React from 'react';\\nimport { RecipeForm } from './components/RecipeForm';\\n\\nexport default function App() {\\n  return <RecipeForm />;\\n}"
  },
  {
    "path": "src/components/RecipeForm.tsx",
    "content": "import React from 'react';\\nimport { Recipe } from '../types';\\n\\nexport const RecipeForm = () => {\\n  return <div>Recipe Form</div>;\\n}"
  },
  {
    "path": "src/types/index.ts",
    "content": "export interface Recipe {\\n  id: number;\\n  title: string;\\n}"
  }
]

CRITICAL RULES - MUST FOLLOW:
1. Return ONLY the raw JSON array - NO markdown code blocks, NO explanations
2. Every component imported in App.tsx MUST have its own file in the array
3. If App.tsx imports "./components/TaskItem", you MUST include src/components/TaskItem.tsx
4. If App.tsx imports "./components/AddTaskForm", you MUST include src/components/AddTaskForm.tsx
5. Create ALL files for ALL imports - NO EXCEPTIONS
6. Escape newlines as \\n and quotes as \\"
7. Start your response with [ and end with ]

EFFICIENCY RULES:
- Generate ONLY files that are NECESSARY for the requirements
- DON'T create extra components, hooks, or utilities "just in case"
- DON'T add features not explicitly requested
- Keep the file structure simple and focused on the core requirement
- If the app can work with fewer files, use fewer files`;
  }

  private buildUserPromptMultiFile(request: AIGenerationRequest): string {
    let prompt = `Create a complete React application with the following requirements:\n\n`;

    prompt += `DESCRIPTION: ${request.prompt}\n\n`;

    if (request.features.length > 0) {
      prompt += `REQUIRED FEATURES:\n`;
      request.features.forEach(feature => {
        prompt += `- ${feature}\n`;
      });
      prompt += '\n';
    }

    if (request.context) {
      prompt += `ADDITIONAL CONTEXT: ${request.context}\n\n`;
    }

    prompt += `CRITICAL REMINDERS:
- Generate a COMPLETE file structure
- Create ALL imported components in separate files
- Put types in src/types/index.ts
- Put utilities in src/utils/*.ts
- Put custom hooks in src/hooks/*.ts
- Return the result as a JSON array of files
- Make it production-ready and fully functional`;

    return prompt;
  }

  private parseMultiFileResponse(content: string): {
    files: { path: string; content: string }[];
    method: 'json' | 'markdown' | 'fallback';
    warning?: string;
  } {
    try {
      // Strategy 1: Try to parse as JSON
      let jsonContent = content.trim();

      // Remove ```json and ``` markers
      jsonContent = jsonContent.replace(/^```json\s*/i, '').replace(/```\s*$/, '');

      // Try to extract JSON array if wrapped in other text
      const jsonMatch = jsonContent.match(/\[\s*\{[\s\S]*\}\s*\]/);
      if (jsonMatch) {
        jsonContent = jsonMatch[0];
      }

      const files = JSON.parse(jsonContent);

      if (!Array.isArray(files)) {
        throw new Error('Response is not an array');
      }

      // Validate each file has path and content
      const validFiles = files.filter(f => f.path && f.content);

      if (validFiles.length === 0) {
        throw new Error('No valid files in JSON response');
      }

      this.logger.info('AICodeGenerator', `Successfully parsed ${validFiles.length} files from JSON`);
      return {
        files: validFiles,
        method: 'json'
      };
    } catch (error) {
      this.logger.warning('AICodeGenerator', 'JSON parsing failed, trying markdown extraction', {
        error: error instanceof Error ? error.message : 'Unknown error'
      });

      // Strategy 2: Try to extract files from markdown code blocks
      const markdownFiles = this.extractFilesFromMarkdown(content);
      if (markdownFiles.length > 0) {
        this.logger.info('AICodeGenerator', `Extracted ${markdownFiles.length} files from markdown`);
        return {
          files: markdownFiles,
          method: 'markdown',
          warning: `⚠️ File parsing used markdown extraction fallback. The AI response was not in the expected JSON format. Generated ${markdownFiles.length} file(s).`
        };
      }

      // Strategy 3: Last resort - return as single file with imports removed
      this.logger.error('AICodeGenerator', '❌ All parsing strategies failed, falling back to single file');

      // Remove local imports from the content
      const cleanedContent = this.stripLocalImports(content);

      return {
        files: [{
          path: 'src/App.tsx',
          content: cleanedContent
        }],
        method: 'fallback',
        warning: `⚠️ CRITICAL: Failed to parse multi-file structure. The AI response could not be properly parsed as JSON or markdown.

All code has been combined into a single file (src/App.tsx) with local imports removed. This may result in a non-functional application.

Suggestions to fix:
1. Try regenerating with a more specific prompt
2. Ask for "a complete multi-file React application with separate component files"
3. Specify the exact file structure you want
4. Consider using orchestration mode for complex applications`
      };
    }
  }

  private extractFilesFromMarkdown(content: string): { path: string; content: string }[] {
    const files: { path: string; content: string }[] = [];

    // Match patterns like: **src/App.tsx** or **index.html** or ### src/components/Button.tsx
    // followed by code blocks
    // Updated to match both src/ files AND root files (index.html, package.json, etc.)
    const filePattern = /(?:\*\*|###)\s*([^\s*\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.ts|config\.js))\s*(?:\*\*)?[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html)?\s*([\s\S]*?)```/gi;

    let match;
    while ((match = filePattern.exec(content)) !== null) {
      const path = match[1].trim();
      const fileContent = match[2].trim();

      if (path && fileContent) {
        files.push({ path, content: fileContent });
      }
    }

    this.logger.info('AICodeGenerator', `extractFilesFromMarkdown found ${files.length} files`, {
      filePaths: files.map(f => f.path)
    });

    return files;
  }

  private stripLocalImports(code: string): string {
    const lines = code.split('\n');
    const filteredLines = lines.filter(line => {
      const trimmed = line.trim();
      // Remove lines with local imports
      if (trimmed.startsWith('import') && /from\s+['"]\.\.?\//.test(trimmed)) {
        return false;
      }
      return true;
    });
    return filteredLines.join('\n');
  }

  private extractDependenciesFromFiles(files: { path: string; content: string }[]): string[] {
    const allDeps = new Set<string>();

    files.forEach(file => {
      const deps = this.extractDependencies(file.content);
      deps.forEach(dep => allDeps.add(dep));
    });

    return Array.from(allDeps);
  }

  private extractDependencies(code: string): string[] {
    const dependencies: string[] = [];

    // Common dependencies to check for
    const dependencyMap: Record<string, string> = {
      'useState': 'react',
      'useEffect': 'react',
      'useCallback': 'react',
      'useMemo': 'react',
      'useRef': 'react',
      'framer-motion': 'framer-motion',
      'react-router': 'react-router-dom',
      'axios': 'axios',
      'date-fns': 'date-fns',
      'lodash': 'lodash',
      'uuid': 'uuid',
      'react-hook-form': 'react-hook-form',
      'zod': 'zod',
      'recharts': 'recharts',
      'lucide-react': 'lucide-react',
      'clsx': 'clsx',
      'tailwind-merge': 'tailwind-merge',
    };

    // Check for imports and usage
    for (const [importName, packageName] of Object.entries(dependencyMap)) {
      if (code.includes(importName) && !dependencies.includes(packageName)) {
        dependencies.push(packageName);
      }
    }

    // Always include React dependencies
    if (!dependencies.includes('react')) {
      dependencies.push('react');
    }
    if (!dependencies.includes('react-dom')) {
      dependencies.push('react-dom');
    }

    return dependencies;
  }

  private ensureRequiredFiles(
    files: { path: string; content: string }[],
    dependencies: string[],
    componentName: string
  ): { path: string; content: string }[] {
    const result = [...files];
    const existingPaths = new Set(files.map(f => f.path));

    // Ensure package.json
    if (!existingPaths.has('package.json')) {
      const depObj: Record<string, string> = {
        'react': '^18.3.1',
        'react-dom': '^18.3.1',
      };

      // Add detected dependencies
      dependencies.forEach(dep => {
        if (dep === 'framer-motion') depObj[dep] = '^11.13.1';
        else if (dep === 'lucide-react') depObj[dep] = '^0.453.0';
        else if (dep === 'clsx') depObj[dep] = '^2.1.1';
        else if (dep === 'tailwind-merge') depObj[dep] = '^2.5.4';
        else if (dep === 'date-fns') depObj[dep] = '^3.6.0';
        else if (dep === 'recharts') depObj[dep] = '^2.13.0';
        else if (dep === 'react-hook-form') depObj[dep] = '^7.53.1';
        else if (dep === 'zod') depObj[dep] = '^3.25.76';
        else if (dep === 'react-router-dom') depObj[dep] = '^6.26.0';
        else if (!depObj[dep]) depObj[dep] = 'latest';
      });

      result.push({
        path: 'package.json',
        content: JSON.stringify({
          name: componentName.toLowerCase().replace(/\s+/g, '-'),
          version: '0.1.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview'
          },
          dependencies: depObj,
          devDependencies: {
            '@types/react': '^18.3.18',
            '@types/react-dom': '^18.3.5',
            '@vitejs/plugin-react': '^4.3.4',
            'autoprefixer': '^10.4.20',
            'postcss': '^8.4.47',
            'tailwindcss': '^3.4.14',
            'typescript': '^5.7.2',
            'vite': '^6.0.11'
          }
        }, null, 2)
      });
    }

    // Ensure index.html
    if (!existingPaths.has('index.html')) {
      result.push({
        path: 'index.html',
        content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${componentName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`
      });
    }

    // Ensure vite.config.ts
    if (!existingPaths.has('vite.config.ts')) {
      result.push({
        path: 'vite.config.ts',
        content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    open: true
  }
});`
      });
    }

    // Ensure tsconfig.json
    if (!existingPaths.has('tsconfig.json')) {
      result.push({
        path: 'tsconfig.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2020',
            useDefineForClassFields: true,
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowImportingTsExtensions: true,
            isolatedModules: true,
            moduleDetection: 'force',
            noEmit: true,
            jsx: 'react-jsx',
            strict: true,
            noUnusedLocals: true,
            noUnusedParameters: true,
            noFallthroughCasesInSwitch: true,
            noUncheckedSideEffectImports: true
          },
          include: ['src']
        }, null, 2)
      });
    }

    // Ensure tsconfig.node.json (required by vite.config.ts)
    if (!existingPaths.has('tsconfig.node.json')) {
      result.push({
        path: 'tsconfig.node.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2022',
            lib: ['ES2023'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowSyntheticDefaultImports: true,
            strict: true,
            resolveJsonModule: true,
            isolatedModules: true,
            moduleDetection: 'force',
            noEmit: true
          },
          include: ['vite.config.ts']
        }, null, 2)
      });
    }

    // Ensure tailwind.config.js
    if (!existingPaths.has('tailwind.config.js')) {
      result.push({
        path: 'tailwind.config.js',
        content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
      });
    }

    // Ensure postcss.config.js
    if (!existingPaths.has('postcss.config.js')) {
      result.push({
        path: 'postcss.config.js',
        content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
      });
    }

    // Ensure src/main.tsx if not present
    if (!existingPaths.has('src/main.tsx')) {
      result.push({
        path: 'src/main.tsx',
        content: `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);`
      });
    }

    // Ensure src/index.css if not present
    if (!existingPaths.has('src/index.css')) {
      result.push({
        path: 'src/index.css',
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}`
      });
    }

    this.logger.info('AICodeGenerator', `Ensured all required files. Total files: ${result.length}`, {
      addedFiles: result.length - files.length
    });

    return result;
  }

  async generateHooks(componentName: string, features: string[]): Promise<string> {
    try {
      const systemPrompt = `You are an expert React developer. Generate custom hooks for a React component.

Create TypeScript custom hooks that would be useful for a "${componentName}" component with these features: ${features.join(', ')}.

Return ONLY the hook code, no explanations.`;

      const userPrompt = `Generate useful custom hooks for the ${componentName} component. Focus on hooks that would be commonly used with these features: ${features.join(', ')}.`;

      const response = await this.anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 2000,
        temperature: 0.7,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      });

      return response.content[0]?.type === 'text' ? response.content[0].text : '';
    } catch (error) {
      this.logger.error('AICodeGenerator', 'Failed to generate hooks', { error });
      return '';
    }
  }

  async generateTypes(componentName: string, features: string[]): Promise<string> {
    try {
      const systemPrompt = `You are an expert TypeScript developer. Generate TypeScript type definitions for a React component.

Create comprehensive TypeScript interfaces and types for a "${componentName}" component with these features: ${features.join(', ')}.

Return ONLY the TypeScript type definitions, no explanations.`;

      const userPrompt = `Generate TypeScript types and interfaces for the ${componentName} component. Include all necessary types for the features: ${features.join(', ')}.`;

      const response = await this.anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 1500,
        temperature: 0.7,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      });

      return response.content[0]?.type === 'text' ? response.content[0].text : '';
    } catch (error) {
      this.logger.error('AICodeGenerator', 'Failed to generate types', { error });
      return '';
    }
  }

}

// Export singleton instance
export const aiCodeGenerator = new AICodeGenerator();
