import Anthropic from '@anthropic-ai/sdk';
import { Logger } from '../utils/Logger';
import { RateLimiter } from '../utils/RateLimiter';
import { multiModelAI, AIRequest } from './MultiModelAIService';
import { PromptManager } from './PromptManager';

export interface AIGenerationRequest {
  prompt: string;
  componentName: string;
  features: string[];
  styling?: {
    animations: boolean;
    theme: string;
  };
  context?: string;
  modelPreference?: 'speed' | 'quality' | 'cost';
  provider?: 'anthropic' | 'openai' | 'gemini' | 'auto';
  orchestrated?: boolean; // If true, skip internal prompt building (orchestrator already built prompts)
  systemPrompt?: string; // Optional pre-built system prompt from orchestrator
}

export interface AIGenerationResponse {
  success: boolean;
  code?: string; // Main component code (for backwards compatibility)
  files?: { path: string; content: string }[]; // Multi-file support
  dependencies: string[];
  error?: string;
  warning?: string; // For non-fatal issues like parsing fallbacks
  parseWarning?: string; // Specific warning about file parsing
  metadata?: {
    provider: string;
    model: string;
    responseTime: number;
    tokens: number;
    cost: number;
    parsingMethod?: 'json' | 'markdown' | 'fallback';
  };
}

export class AICodeGenerator {
  private anthropic: Anthropic;
  private logger: Logger;
  private limiter: RateLimiter;
  private promptManager: PromptManager;

  constructor() {
    this.anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
    this.logger = new Logger(process.cwd());
    this.logger.initialize().catch(console.error);
    this.limiter = new RateLimiter(5);
    this.promptManager = PromptManager.getInstance();
  }

  async generateComponent(request: AIGenerationRequest): Promise<AIGenerationResponse> {
    try {
      console.log('🎨 AICodeGenerator: Starting component generation');
      console.log('📝 AICodeGenerator: Request:', {
        componentName: request.componentName,
        features: request.features,
        promptLength: request.prompt.length,
        orchestrated: request.orchestrated || false
      });

      this.logger.info('AICodeGenerator', 'Generating component with multi-model AI', {
        componentName: request.componentName,
        features: request.features,
        provider: request.provider || 'auto',
        preference: request.modelPreference || 'quality',
        orchestrated: request.orchestrated || false
      });

      let systemPrompt: string;
      let userPrompt: string;

      if (request.orchestrated) {
        // PASS-THROUGH MODE: Orchestrator already built comprehensive prompts
        // Use them directly to avoid double-prompting confusion
        console.log('🎯 AICodeGenerator: ORCHESTRATED MODE - Using pre-built prompts');
        systemPrompt = request.systemPrompt || '';
        userPrompt = request.prompt; // Use orchestrator's prompt exactly as-is
        console.log('📊 AICodeGenerator: Orchestrated prompt sizes:', {
          system: systemPrompt.length,
          user: userPrompt.length
        });
      } else {
        // LEGACY MODE: Build prompts internally (for direct calls not from orchestrator)
        console.log('🏗️ AICodeGenerator: LEGACY MODE - Building prompts internally (with database lookup)');
        systemPrompt = await this.buildSystemPromptMultiFile(request);
        userPrompt = this.buildUserPromptMultiFile(request);
        console.log('📊 AICodeGenerator: Built prompt sizes:', {
          system: systemPrompt.length,
          user: userPrompt.length
        });
      }

      // Use multi-model AI service
      // Increase maxTokens for complex apps that generate many files
      const aiRequest: AIRequest = {
        prompt: userPrompt,
        systemPrompt,
        maxTokens: 16000, // INCREASED: Was 8000, now 16000 to handle complex apps with many files
        temperature: 0.3, // LOWERED: More deterministic for structured JSON output
        useCase: 'code_generation',
        priority: request.modelPreference || 'quality'
      };

      console.log('🤖 AICodeGenerator: Calling multiModelAI.generate()...');
      const startTime = Date.now();
      const response = await multiModelAI.generate(aiRequest);
      const elapsed = Date.now() - startTime;
      console.log(`✅ AICodeGenerator: multiModelAI.generate() completed in ${elapsed}ms`);

      if (!response.content) {
        throw new Error('No code generated by AI');
      }

      // CRITICAL VALIDATION: Check if response is valid JSON array BEFORE processing
      let trimmedContent = response.content.trim();
      
      // Strip markdown code blocks if present (AI sometimes wraps JSON in ```json ... ```)
      if (trimmedContent.startsWith('```')) {
        console.log('🔧 [AICodeGenerator] Detected markdown code block wrapper, stripping...');
        // Remove opening ```json or ```
        trimmedContent = trimmedContent.replace(/^```(?:json)?\s*\n?/i, '');
        // Remove closing ```
        trimmedContent = trimmedContent.replace(/\n?```\s*$/i, '');
        trimmedContent = trimmedContent.trim();
        console.log('🔧 [AICodeGenerator] After stripping markdown, starts with:', trimmedContent.substring(0, 50));
        // Update response.content to use cleaned version
        response.content = trimmedContent;
      }
      
      const startsWithArray = trimmedContent.startsWith('[');
      let endsWithArray = trimmedContent.trimEnd().endsWith(']');
      const containsMarkdown = response.content.includes('```');
      const containsExplanation = /^(Here|I|The|Let|This)/i.test(trimmedContent);

      // Debug: Log response preview for troubleshooting
      console.error('=== AI RESPONSE DEBUG START ===');
      console.error(`Total length: ${response.content.length} chars`);
      console.error(`Starts with [: ${startsWithArray}`);
      console.error(`Ends with ]: ${endsWithArray}`);
      console.error(`Contains markdown: ${containsMarkdown}`);
      console.error(`Contains explanation: ${containsExplanation}`);
      console.error('--- FIRST 1000 CHARS ---');
      console.error(response.content.substring(0, 1000));
      console.error('--- LAST 1000 CHARS ---');
      console.error(response.content.substring(Math.max(0, response.content.length - 1000)));
      console.error('=== AI RESPONSE DEBUG END ===');

      // Handle truncated JSON responses (starts with [ but doesn't end with ])
      if (startsWithArray && !endsWithArray) {
        console.warn('⚠️ [AICodeGenerator] Response appears truncated (starts with [ but missing closing ])');
        console.warn('🔧 [AICodeGenerator] Attempting to fix by adding closing bracket...');
        
        // Try to find the last complete JSON object and add closing bracket
        // Count open brackets vs close brackets
        const openBrackets = (trimmedContent.match(/\[/g) || []).length;
        const closeBrackets = (trimmedContent.match(/\]/g) || []).length;
        const missingBrackets = openBrackets - closeBrackets;
        
        if (missingBrackets > 0) {
          console.log(`🔧 [AICodeGenerator] Missing ${missingBrackets} closing bracket(s), adding...`);
          // Remove any trailing incomplete content and add closing bracket
          // Find the last complete JSON object by looking for the last }
          const lastCompleteObject = trimmedContent.lastIndexOf('}');
          if (lastCompleteObject > 0) {
            // Keep everything up to and including the last complete object, then add closing bracket
            trimmedContent = trimmedContent.substring(0, lastCompleteObject + 1);
            // Add missing closing brackets
            trimmedContent += '\n' + ']'.repeat(missingBrackets);
            response.content = trimmedContent;
            endsWithArray = true;
            console.log('✅ [AICodeGenerator] Fixed truncated JSON by adding closing bracket(s)');
          } else {
            // If we can't find a complete object, just add the closing bracket
            trimmedContent = trimmedContent.trimEnd() + '\n]';
            response.content = trimmedContent;
            endsWithArray = true;
            console.log('✅ [AICodeGenerator] Added closing bracket to incomplete JSON');
          }
        }
      }

      // REJECT non-JSON responses immediately (after stripping markdown and fixing truncation)
      if (!startsWithArray || !endsWithArray) {
        const errorMsg = `AI did not return valid JSON array format. Response started with: "${trimmedContent.substring(0, 50)}"`;
        console.error(`❌ ${errorMsg}`);
        this.logger.error('AICodeGenerator', errorMsg, {
          startsWithArray,
          endsWithArray,
          containsMarkdown,
          containsExplanation,
          preview: trimmedContent.substring(0, 200),
          responseLength: response.content.length
        });
        throw new Error('AI returned invalid format. Expected JSON array but got: ' + (containsMarkdown ? 'Markdown' : containsExplanation ? 'Text explanation' : 'Unknown format'));
      }

      // Warn about markdown blocks (we'll try to extract but it's suboptimal)
      if (containsMarkdown) {
        console.warn('⚠️ WARNING: AI response contains markdown blocks. This indicates the prompt was not followed correctly.');
        this.logger.warning('AICodeGenerator', 'AI included markdown in JSON response', {
          provider: response.provider,
          model: response.model
        });
      }

      // Parse the multi-file JSON response (use cleaned content)
      const parseResult = this.parseMultiFileResponse(response.content);

      if (parseResult.files.length === 0) {
        throw new Error('AI generated no files');
      }

      // STEP 1: AI-powered syntax fixing (replaces regex patterns)
      // Instead of hardcoded regex patterns, we use AI to intelligently fix syntax errors.
      // Benefits:
      // - AI understands context and can handle edge cases regex misses
      // - Uses esbuild to catch real compilation errors (not just pattern matching)
      // - More maintainable - no need to update regex patterns for new error types
      // - Better accuracy - AI can distinguish between valid and invalid semicolons
      console.log('🔧 Validating and fixing syntax errors with AI...');
      const { AISyntaxFixer } = await import('./AISyntaxFixer');
      const aiFixer = new AISyntaxFixer();
      const fixResult = await aiFixer.validateAndFix(parseResult.files);
      
      if (fixResult.success) {
        parseResult.files = fixResult.fixedFiles;
        console.log(`✅ AI fixed all syntax errors (${fixResult.fixAttempts} attempt(s))`);
      } else if (fixResult.remainingErrors.length > 0) {
        console.warn(`⚠️ AI fixed some errors but ${fixResult.remainingErrors.length} remain - using fixed files anyway`);
        parseResult.files = fixResult.fixedFiles; // Use partially fixed files
      }

      // STEP 2: Strip restrictive CSP from index.html files
      // WebContainer needs to load scripts, so we can't have default-src 'none'
      parseResult.files = parseResult.files.map(file => {
        if (file.path.endsWith('index.html') || file.path.endsWith('.html')) {
          let content = file.content;
          // Remove any CSP meta tags with restrictive policies
          const cspPattern = /<meta[^>]*http-equiv\s*=\s*["']?Content-Security-Policy["']?[^>]*>/gi;
          if (cspPattern.test(content)) {
            console.log(`🔒 Removing restrictive CSP from ${file.path}`);
            content = content.replace(cspPattern, '<!-- CSP removed for WebContainer compatibility -->');
          }
          return { ...file, content };
        }
        return file;
      });

      // STEP 3: THEN validate that files don't contain JSON structures
      console.log('🔍 Validating file contents...');
      parseResult.files = parseResult.files.map(file => {
        const trimmed = file.content.trim();

        // IMPROVED: More precise JSON-inside-JSON detection
        // Only flag if it looks like the ENTIRE file is our multi-file JSON structure
        // Not just TypeScript code that happens to have "path" or "content" fields

        // Pattern 1: File is a JSON array like: [{"path": "...", "content": "..."}]
        const looksLikeFileArray = trimmed.startsWith('[') &&
          /^\s*\[\s*\{\s*"path"\s*:\s*"[^"]+"\s*,\s*"content"\s*:/.test(trimmed) &&
          trimmed.endsWith(']');

        // Pattern 2: File is a single JSON object like: {"path": "...", "content": "..."}
        const looksLikeSingleFileObject = /^\s*\{\s*"path"\s*:\s*"[^"]+"\s*,\s*"content"\s*:\s*"/.test(trimmed) &&
          !trimmed.includes('export') && // TypeScript exports are NOT JSON
          !trimmed.includes('interface') && // TypeScript interfaces are NOT JSON
          !trimmed.includes('type') && // TypeScript types are NOT JSON
          !trimmed.includes('import'); // TypeScript imports are NOT JSON

        if (looksLikeFileArray || looksLikeSingleFileObject) {
          console.error(`❌ CRITICAL ERROR: ${file.path} contains JSON structure instead of code!`);
          console.error(`First 500 chars: ${trimmed.substring(0, 500)}`);

          // Try to extract the actual code if it's nested JSON
          try {
            const parsed = JSON.parse(trimmed);
            if (Array.isArray(parsed) && parsed[0]?.path && parsed[0]?.content) {
              // This is the entire JSON array embedded in a file - extract the matching file
              const match = parsed.find((f: any) => f.path === file.path);
              if (match?.content) {
                console.log(`✅ Recovered actual content for ${file.path} from nested JSON`);
                return { ...file, content: match.content };
              }
            } else if (parsed.content && typeof parsed.content === 'string') {
              // Single file JSON object
              console.log(`✅ Recovered actual content for ${file.path} from JSON wrapper`);
              return { ...file, content: parsed.content };
            }
          } catch (e) {
            console.error(`Failed to recover content from malformed JSON in ${file.path}`);
          }

          throw new Error(`CRITICAL: ${file.path} contains JSON metadata instead of actual code. The AI generated malformed output.`);
        }
        return file;
      });
      console.log('✅ File validation passed');

      // Extract all dependencies from all files
      const dependencies = this.extractDependenciesFromFiles(parseResult.files);

      this.logger.info('AICodeGenerator', 'Multi-file component generated successfully', {
        filesCount: parseResult.files.length,
        dependencies,
        provider: response.provider,
        model: response.model,
        responseTime: response.responseTime,
        cost: response.usage.cost,
        parsingMethod: parseResult.method,
      });

      // Validate and fix missing imports
      const validatedFiles = this.validateAndFixImports(parseResult.files);

      // Ensure all required configuration files are present
      const filesWithRequired = this.ensureRequiredFiles(validatedFiles, dependencies, request.componentName);
      
      // Sanitize CSS to remove undefined variable patterns (border-border, bg-background, etc.)
      const sanitizedCSSFiles = this.sanitizeCSSFiles(filesWithRequired);
      
      // Sanitize Timer/Counter code to prevent NaN display issues
      const completeFiles = this.sanitizeTimerCode(sanitizedCSSFiles);

      const result: AIGenerationResponse = {
        success: true,
        files: completeFiles,
        code: completeFiles.find(f => f.path === 'src/App.tsx')?.content || '', // Backwards compatibility
        dependencies,
        metadata: {
          provider: response.provider,
          model: response.model,
          responseTime: response.responseTime,
          tokens: response.usage.totalTokens,
          cost: response.usage.cost,
          parsingMethod: parseResult.method,
        },
      };

      // Add warning if fallback parsing was used
      if (parseResult.warning) {
        result.parseWarning = parseResult.warning;
        result.warning = parseResult.warning;
      }

      return result;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      this.logger.error('AICodeGenerator', 'Failed to generate component', {
        error: errorMessage,
      });

      return {
        success: false,
        code: '',
        files: [],
        dependencies: [],
        error: errorMessage,
      };
    }
  }

  private buildSystemPrompt(request: AIGenerationRequest): string {
    return `You are an expert React developer specializing in creating modern, functional web applications.

Your task is to generate a complete, working React component based on the user's requirements.

CRITICAL REQUIREMENTS:
- Use React 18+ with TypeScript
- Use modern React patterns (hooks, functional components)
- Include proper TypeScript types and interfaces
- Use Tailwind CSS for styling (with inline classes, use modern gradients and shadows)
- Make the component fully functional and interactive with realistic data
- Include proper error handling and loading states
- Every visible navigation item, tab, or page label must be functional. If you render labels such as Gallery, Community, About, Cards, Packs, Settings, or similar, implement active view state with onClick handlers, real anchor sections with matching ids, or router Links/Routes. Never render decorative href="#" links or nav buttons without handlers.

🚨 CRITICAL SYNTAX RULES - VERIFY BEFORE RESPONDING 🚨
ABSOLUTELY NO SYNTAX ERRORS ALLOWED:
❌ NEVER write "return (;" - this is a CRITICAL ERROR
❌ NEVER put semicolons immediately after opening parentheses: (;
❌ NEVER put semicolons immediately after opening braces: {;
❌ NEVER put semicolons immediately after opening brackets: [;
✅ ALWAYS verify your code has valid JavaScript/TypeScript syntax
✅ ALWAYS check that parentheses, braces, and brackets are properly closed
✅ DOUBLE-CHECK every return statement for correct syntax
- Use semantic HTML elements
- Make it responsive and accessible (works on mobile, tablet, desktop)
- Add smooth transitions and professional UI/UX
- Include keyboard navigation and ARIA labels
- Use modern design patterns (cards, modals, toasts, etc.)
- Add data persistence with localStorage where appropriate

🚨 CRITICAL - SINGLE FILE COMPONENT RULE 🚨
This is the MOST IMPORTANT requirement - if you violate this, the app will BREAK:

❌ ABSOLUTELY FORBIDDEN - You MUST NOT do these:
- NO "import ... from './components/...'"
- NO "import ... from './utils/...'"
- NO "import ... from './hooks/...'"
- NO "import ... from './types/...'"
- NO "import ... from './lib/...'"
- NO "import ... from './services/...'"
- NO relative imports starting with "./" or "../"

✅ ALLOWED - You CAN ONLY import from:
- "react" and "react-dom"
- npm packages: "framer-motion", "lucide-react", "clsx", "date-fns", etc.

✅ REQUIRED - Put EVERYTHING in ONE file:
- Define ALL interfaces and types at the top of the file
- Define ALL helper functions in the file
- Define ALL sub-components in the file (before the main component)
- Define ALL utilities in the file
- Define ALL constants in the file
- The ONLY exports should be: "export default function App()"

Example CORRECT structure:
\`\`\`typescript
import React, { useState } from 'react';

// Types
interface Recipe {
  id: number;
  title: string;
}

// Helper functions
const formatDate = (date: Date) => date.toLocaleDateString();

// Sub-components (if needed)
const RecipeCard = ({ recipe }: { recipe: Recipe }) => (
  <div>{recipe.title}</div>
);

// Main component - MUST be named "App"
export default function App() {
  return <div>...</div>;
}
\`\`\`

COMPONENT SPECIFICATIONS:
- Component Name: App (always use "App" as the exported component name)
- Features: ${(request.features || []).join(', ')}
- Theme: ${request.styling?.theme || 'light'}
- Animations: ${request.styling?.animations ? 'Include smooth animations' : 'No animations needed'}

OUTPUT FORMAT:
Return ONLY the complete React component code. Do not include markdown code fences (\`\`\`), explanations, or any other text. Just the raw TypeScript/React code.

The component should be a complete, functional implementation in ONE SINGLE FILE.`;
  }

  private buildUserPrompt(request: AIGenerationRequest): string {
    let prompt = `Create a React component with the following requirements:\n\n`;

    prompt += `DESCRIPTION: ${request.prompt}\n\n`;

    if (request.features.length > 0) {
      prompt += `REQUIRED FEATURES:\n`;
      request.features.forEach(feature => {
        prompt += `- ${feature}\n`;
      });
      prompt += '\n';
    }

    if (request.context) {
      prompt += `ADDITIONAL CONTEXT: ${request.context}\n\n`;
    }

    prompt += `CRITICAL REMINDERS:
- Create a SINGLE, SELF-CONTAINED file
- NO local imports (no "./components/...", no "./utils/...", etc.)
- Put ALL types, sub-components, and helpers IN THE SAME FILE
- Export the main component as: "export default function App()"
- Make it fully functional and production-ready
- If you include navigation, tabs, or multiple pages/sections, every visible item must switch view, scroll to a real section, or route to a real page. No decorative nav items, href="#", or inert buttons.`;

    return prompt;
  }

  /**
   * Try to load system prompt from database first, fallback to hardcoded version
   * This ensures database updates take effect immediately
   */
  private async buildSystemPromptMultiFile(request: AIGenerationRequest): Promise<string> {
    // Try loading from database first
    try {
      console.log('🔍 [AICodeGenerator] Attempting to load prompt from database...');

      const dbPrompt = await this.promptManager.buildSystemPrompt(
        'code_generator.code_generator',
        {
          userContext: request.prompt,
          componentName: request.componentName,
          features: (request.features || []).join(', '),
          styling: JSON.stringify(request.styling || {})
        },
        {
          includeGuidelines: true
          // Note: forceRefresh is not available in buildSystemPrompt options
          // Caching is handled internally by PromptManager
        }
      );

      if (dbPrompt && dbPrompt.systemPrompt) {
        console.log('✅ [AICodeGenerator] Using DATABASE prompt for code generation');
        console.log('📊 [AICodeGenerator] Database prompt length:', dbPrompt.systemPrompt.length);
        return dbPrompt.systemPrompt;
      } else {
        console.warn('⚠️ [AICodeGenerator] Database prompt was empty, falling back to hardcoded');
      }
    } catch (error) {
      console.error('❌ [AICodeGenerator] Failed to load database prompt, using hardcoded fallback:', error);
    }

    // Fallback to hardcoded prompt (emergency only)
    console.log('🏗️ [AICodeGenerator] Using HARDCODED fallback prompt');
    return this.buildHardcodedSystemPrompt(request);
  }

  /**
   * Hardcoded system prompt as EMERGENCY fallback only
   * 
   * ARCHITECTURAL NOTE: This should RARELY be used. The primary code path
   * should use database prompts from PromptManager. If this is being called
   * frequently, it indicates the database prompts need to be updated.
   * 
   * This is intentionally MINIMAL - all detailed coding rules should be
   * in the agent's systemPrompt stored in the database.
   */
  private buildHardcodedSystemPrompt(request: AIGenerationRequest): string {
    this.logger.warning('AICodeGenerator', '⚠️ Using HARDCODED fallback prompt - update database prompts!');
    
    return `You are a senior React TypeScript developer. Generate production-ready code.

COMPONENT: ${request.componentName}
FEATURES: ${(request.features || []).join(', ')}
THEME: ${request.styling?.theme || 'light'}

CRITICAL RULES:
1. Response format: JSON array ONLY - [{"path": "...", "content": "..."}]
2. Start with [ and end with ] - NO markdown, NO explanations
3. Components in src/components/ use NAMED exports: export function Name() {}
4. App.tsx uses DEFAULT export: export default function App() {}
5. Match export type to import type (named import = named export)
6. All imports must have corresponding files in your JSON array
7. Every visible navigation item, tab, or page label must be functional:
   - Use activePage/activeTab state + onClick handlers, real anchor ids, or react-router-dom routes
   - Create/render every page or section named in the navbar
   - Never use decorative href="#" links or buttons without onClick
8. NO syntax errors - especially:
   - No semicolons after { or before : in ternaries
   - No interface Name {; or return {; patterns
   - All brackets/braces/parens must be balanced

**NULL-SAFETY (CRITICAL - PREVENTS RUNTIME CRASHES):**
- ALWAYS use optional chaining: object?.property instead of object.property
- ALWAYS use nullish coalescing: value ?? defaultValue for safe defaults
- ALWAYS initialize Date objects safely: new Date(value || Date.now())
- ALWAYS check arrays before mapping: (array || []).map(...)
- ALWAYS provide default values for all props and state
- NEVER assume data exists - always check first!
- Example safe date: const date = entry?.date ? new Date(entry.date) : new Date();
- Example safe array: const items = (data?.items || []).filter(i => i?.id);

FILE STRUCTURE:
- src/App.tsx (default export)
- src/components/*.tsx (named exports)
- src/types/index.ts (if needed)
- package.json, tsconfig.json, vite.config.ts, index.html

Start your response with [`;
  }

  private buildUserPromptMultiFile(request: AIGenerationRequest): string {
    let prompt = `Create a complete React application with the following requirements:\n\n`;

    prompt += `DESCRIPTION: ${request.prompt}\n\n`;

    if (request.features.length > 0) {
      prompt += `REQUIRED FEATURES:\n`;
      request.features.forEach(feature => {
        prompt += `- ${feature}\n`;
      });
      prompt += '\n';
    }

    if (request.context) {
      prompt += `ADDITIONAL CONTEXT: ${request.context}\n\n`;
    }

    prompt += `CRITICAL REMINDERS:
- Generate a COMPLETE file structure
- Create ALL imported components in separate files
- Put types in src/types/index.ts
- Put utilities in src/utils/*.ts
- Put custom hooks in src/hooks/*.ts
- Return the result as a JSON array of files
- Make it production-ready and fully functional
- If you include navigation, tabs, or multiple pages/sections, every visible item must switch view, scroll to a real section, or route to a real page. No decorative nav items, href="#", or inert buttons.`;

    return prompt;
  }

  private parseMultiFileResponse(content: string): {
    files: { path: string; content: string }[];
    method: 'json' | 'markdown' | 'fallback';
    warning?: string;
  } {
    try {
      // Strategy 1: Try to parse as JSON with multiple extraction attempts
      let jsonContent = content.trim();

      // Remove markdown code blocks - be aggressive
      // Handle cases like: ```json\n[...]\n```
      if (jsonContent.includes('```')) {
        // Extract content between first and last ```
        const codeBlockMatch = jsonContent.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
        if (codeBlockMatch && codeBlockMatch[1]) {
          jsonContent = codeBlockMatch[1].trim();
        } else {
          // Fallback: just remove all ``` markers
          jsonContent = jsonContent.replace(/```(?:json)?/g, '').trim();
        }
      }

      // Remove common AI explanatory text before JSON
      jsonContent = jsonContent.replace(/^(?:Here's?|Here is|I've created|I have created|Below is).*?\n/gim, '');

      // Try multiple JSON extraction strategies
      let jsonMatch = null;

      // Strategy 1a: Find JSON array with greedy matching
      jsonMatch = jsonContent.match(/\[\s*\{[\s\S]*\}\s*\]/);

      // Strategy 1b: If that fails, try to find JSON between [ and ]
      if (!jsonMatch) {
        const firstBracket = jsonContent.indexOf('[');
        const lastBracket = jsonContent.lastIndexOf(']');
        if (firstBracket !== -1 && lastBracket !== -1 && lastBracket > firstBracket) {
          jsonMatch = [jsonContent.substring(firstBracket, lastBracket + 1)];
        }
      }

      if (jsonMatch) {
        jsonContent = jsonMatch[0];
      }

      const files = JSON.parse(jsonContent);

      if (!Array.isArray(files)) {
        throw new Error('Response is not an array');
      }

      // Validate each file has path and content
      const validFiles = files.filter(f => f.path && f.content);

      if (validFiles.length === 0) {
        throw new Error('No valid files in JSON response');
      }

      this.logger.info('AICodeGenerator', `Successfully parsed ${validFiles.length} files from JSON`);
      return {
        files: validFiles,
        method: 'json'
      };
    } catch (error) {
      this.logger.warning('AICodeGenerator', 'JSON parsing failed, trying markdown extraction', {
        error: error instanceof Error ? error.message : 'Unknown error'
      });

      // Strategy 2: Try to extract files from markdown code blocks with multiple patterns
      const markdownFiles = this.extractFilesFromMarkdown(content);
      if (markdownFiles.length > 0) {
        this.logger.info('AICodeGenerator', `Extracted ${markdownFiles.length} files from markdown`);
        return {
          files: markdownFiles,
          method: 'markdown',
          warning: `⚠️ File parsing used markdown extraction fallback. The AI response was not in the expected JSON format. Generated ${markdownFiles.length} file(s).`
        };
      }

      // Strategy 3: Try to extract ANY code blocks and infer filenames
      this.logger.warning('AICodeGenerator', 'Trying aggressive code block extraction as last resort');
      const aggressiveFiles = this.extractAnyCodeBlocks(content);
      if (aggressiveFiles.length > 0) {
        this.logger.info('AICodeGenerator', `Extracted ${aggressiveFiles.length} files via aggressive extraction`);
        return {
          files: aggressiveFiles,
          method: 'markdown',
          warning: `⚠️ Used aggressive code extraction. File names may not be accurate. Generated ${aggressiveFiles.length} file(s).`
        };
      }

      // Strategy 4: Last resort - return as single file with imports removed
      this.logger.error('AICodeGenerator', '❌ All parsing strategies failed, falling back to single file', {
        contentSample: content.substring(0, 500)
      });

      // Remove local imports from the content
      const cleanedContent = this.stripLocalImports(content);

      return {
        files: [{
          path: 'src/App.tsx',
          content: cleanedContent
        }],
        method: 'fallback',
        warning: `⚠️ CRITICAL: Failed to parse multi-file structure. The AI response could not be properly parsed as JSON or markdown.

All code has been combined into a single file (src/App.tsx) with local imports removed. This may result in a non-functional application.

Suggestions to fix:
1. Try regenerating with a more specific prompt
2. Ask for "a complete multi-file React application with separate component files"
3. Specify the exact file structure you want
4. Consider using orchestration mode for complex applications`
      };
    }
  }

  /**
   * Aggressive extraction - try to extract any code blocks and infer filenames
   */
  private extractAnyCodeBlocks(content: string): { path: string; content: string }[] {
    const files: { path: string; content: string }[] = [];

    // Extract all code blocks
    const codeBlockPattern = /```(?:typescript|tsx|javascript|jsx|ts|js)?\s*([\s\S]*?)```/gi;
    let match;
    let blockIndex = 0;

    while ((match = codeBlockPattern.exec(content)) !== null) {
      const code = match[1].trim();

      if (code.length < 20) continue; // Skip tiny blocks

      // Try to infer filename from code content
      let filename = `src/Component${blockIndex}.tsx`;

      // Check if it's a component
      if (code.includes('export default function') || code.includes('export const')) {
        const componentMatch = code.match(/(?:export default function|export const)\s+([A-Z]\w+)/);
        if (componentMatch) {
          filename = `src/components/${componentMatch[1]}.tsx`;
        }
      }
      // Check if it's App.tsx
      else if (code.includes('function App') || code.includes('const App')) {
        filename = 'src/App.tsx';
      }
      // Check if it's types
      else if (code.includes('export interface') || code.includes('export type')) {
        filename = 'src/types/index.ts';
      }
      // Check if it's CSS
      else if (code.includes('@tailwind') || code.includes('.css')) {
        filename = 'src/index.css';
      }
      // Check if it's config
      else if (code.includes('export default {') && (code.includes('plugins') || code.includes('theme'))) {
        filename = 'tailwind.config.js';
      }
      else if (code.includes('"name"') && code.includes('"dependencies"')) {
        filename = 'package.json';
      }

      files.push({ path: filename, content: code });
      blockIndex++;
    }

    return files;
  }

  private extractFilesFromMarkdown(content: string): { path: string; content: string }[] {
    const files: { path: string; content: string }[] = [];

    // Try multiple markdown patterns to be more flexible

    // Pattern 1: **filename** or **path/filename** followed by code block
    const pattern1 = /\*\*\s*([^\s*\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs))\s*\*\*[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    // Pattern 2: ### filename or ## filename (markdown heading) followed by code block
    const pattern2 = /(?:^|\n)#{1,4}\s+([^\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs))[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    // Pattern 3: Filename: or File: filename followed by code block (more lenient)
    const pattern3 = /(?:File(?:name)?|Path):\s*(?:`([^`]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs))`|([^\s\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs)))[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    // Pattern 4: Just code blocks with comments indicating filename
    const pattern4 = /```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)\s*(?:\/\/|\/\*)\s*([^\s\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs)).*?\n([\s\S]*?)```/gi;

    // Pattern 5: Catch-all - any line with a file path followed by a code block (most lenient)
    const pattern5 = /([^\s\n]+\.(?:tsx?|jsx?|css|json|html|js))[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    const patterns = [pattern1, pattern2, pattern3, pattern4, pattern5];

    for (const pattern of patterns) {
      let match;
      while ((match = pattern.exec(content)) !== null) {
        // Different patterns have groups in different positions
        let path: string;
        let fileContent: string;

        if (pattern === pattern3) {
          // Pattern 3 has optional backticks around path
          path = (match[1] || match[2]).trim();
          fileContent = match[3].trim();
        } else {
          path = match[1].trim();
          fileContent = match[2].trim();
        }

        // Clean up the path - remove any markdown formatting
        path = path.replace(/[*_`]/g, '');

        // Skip if we already have this file or if path/content is invalid
        if (!files.find(f => f.path === path) && path && fileContent && fileContent.length > 10) {
          // Validate extracted content for obvious truncation issues
          const validationWarnings = this.validateExtractedCode(fileContent, path);
          if (validationWarnings.length > 0) {
            console.warn(`⚠️  Markdown extraction warnings for ${path}:`);
            validationWarnings.forEach(w => console.warn(`   - ${w}`));
          }

          files.push({ path, content: fileContent });
        }
      }
    }

    this.logger.info('AICodeGenerator', `extractFilesFromMarkdown found ${files.length} files`, {
      filePaths: files.map(f => f.path)
    });

    return files;
  }

  // NOTE: autoFixCommonSyntaxIssues() has been REMOVED (~600 lines of regex patterns)
  // We now use AISyntaxFixer which uses esbuild for validation and AI for intelligent fixes.
  // See server/services/AISyntaxFixer.ts for the new implementation.

  /**
   * Validate extracted code for obvious truncation or corruption issues
   * Returns array of warning messages
   */
  private validateExtractedCode(content: string, filePath: string): string[] {
    const warnings: string[] = [];

    // Skip validation for non-code files
    if (!filePath.match(/\.(tsx?|jsx?)$/)) {
      return warnings;
    }

    // Check 1: Severe bracket/brace imbalance (indicates truncation)
    const openBraces = (content.match(/\{/g) || []).length;
    const closeBraces = (content.match(/\}/g) || []).length;
    const braceDiff = Math.abs(openBraces - closeBraces);
    if (braceDiff > 3) {
      warnings.push(`Severe brace mismatch: ${openBraces} open, ${closeBraces} close (diff: ${braceDiff})`);
    }

    // Check 2: File ends with opening delimiter (likely truncated)
    const lastChars = content.trim().slice(-10);
    if (/[({[][\s]*$/.test(lastChars)) {
      warnings.push(`File ends with opening delimiter - likely truncated`);
    }

    // Check 3: File has "return (" without matching close
    const returnMatches = content.match(/return\s*\(/g);
    if (returnMatches && returnMatches.length > 0) {
      const returnCount = returnMatches.length;
      // Count how many return statements have closing parens on same or next line
      const completeReturns = content.match(/return\s*\([^)]*\)|return\s*\(\s*\n/g);
      const completeCount = completeReturns ? completeReturns.length : 0;
      if (returnCount > completeCount + 2) {
        warnings.push(`Found ${returnCount} "return (" but only ${completeCount} appear complete`);
      }
    }

    return warnings;
  }

  // NOTE: verifySyntaxFixes() has been REMOVED (used only by autoFixCommonSyntaxIssues)
  // We now use AISyntaxFixer.validateAndFix() which uses esbuild for validation.
  // See server/services/AISyntaxFixer.ts for the new implementation.

  private stripLocalImports(code: string): string {
    const lines = code.split('\n');
    const filteredLines = lines.filter(line => {
      const trimmed = line.trim();
      // Remove lines with local imports
      if (trimmed.startsWith('import') && /from\s+['"]\.\.?\//.test(trimmed)) {
        return false;
      }
      return true;
    });
    return filteredLines.join('\n');
  }

  private extractDependenciesFromFiles(files: { path: string; content: string }[]): string[] {
    const allDeps = new Set<string>();

    files.forEach(file => {
      const deps = this.extractDependencies(file.content);
      deps.forEach(dep => allDeps.add(dep));
    });

    return Array.from(allDeps);
  }

  private extractDependencies(code: string): string[] {
    const dependencies: string[] = [];

    // Common dependencies to check for
    const dependencyMap: Record<string, string> = {
      'useState': 'react',
      'useEffect': 'react',
      'useCallback': 'react',
      'useMemo': 'react',
      'useRef': 'react',
      'framer-motion': 'framer-motion',
      'react-router': 'react-router-dom',
      'axios': 'axios',
      'date-fns': 'date-fns',
      'lodash': 'lodash',
      'uuid': 'uuid',
      'react-hook-form': 'react-hook-form',
      'zod': 'zod',
      'recharts': 'recharts',
      'lucide-react': 'lucide-react',
      'clsx': 'clsx',
      'tailwind-merge': 'tailwind-merge',
    };

    // Check for imports and usage
    for (const [importName, packageName] of Object.entries(dependencyMap)) {
      if (code.includes(importName) && !dependencies.includes(packageName)) {
        dependencies.push(packageName);
      }
    }

    // Always include React dependencies
    if (!dependencies.includes('react')) {
      dependencies.push('react');
    }
    if (!dependencies.includes('react-dom')) {
      dependencies.push('react-dom');
    }

    return dependencies;
  }

  private ensureRequiredFiles(
    files: { path: string; content: string }[],
    dependencies: string[],
    componentName: string
  ): { path: string; content: string }[] {
    const result = [...files];
    const existingPaths = new Set(files.map(f => f.path));

    // Required devDependencies that MUST be present for the app to build
    const requiredDevDeps = {
      '@types/react': '^18.3.18',
      '@types/react-dom': '^18.3.5',
      '@vitejs/plugin-react': '^5.0.0',
      'autoprefixer': '^10.4.20',
      'postcss': '^8.4.47',
      'tailwindcss': '^3.4.14',
      'typescript': '^5.7.2',
      'vite': '^7.1.7'
    };

    // Check if this is a monorepo structure (has server/ directory)
    const isMonorepo = result.some(f => f.path.startsWith('server/'));
    const packageJsonPath = isMonorepo ? 'client/package.json' : 'package.json';
    
    // Ensure package.json with proper dependencies (client/package.json for monorepo, package.json for single-package)
    const existingPackageJsonIndex = result.findIndex(f => f.path === packageJsonPath);

    if (existingPackageJsonIndex === -1) {
      // No package.json exists - create one
      const depObj: Record<string, string> = {
        'react': '^18.3.1',
        'react-dom': '^18.3.1',
      };

      // Add detected dependencies
      dependencies.forEach(dep => {
        if (dep === 'framer-motion') depObj[dep] = '^11.13.1';
        else if (dep === 'lucide-react') depObj[dep] = '^0.453.0';
        else if (dep === 'clsx') depObj[dep] = '^2.1.1';
        else if (dep === 'tailwind-merge') depObj[dep] = '^2.5.4';
        else if (dep === 'date-fns') depObj[dep] = '^3.6.0';
        else if (dep === 'recharts') depObj[dep] = '^2.13.0';
        else if (dep === 'react-hook-form') depObj[dep] = '^7.53.1';
        else if (dep === 'zod') depObj[dep] = '^3.25.76';
        else if (dep === 'react-router-dom') depObj[dep] = '^6.26.0';
        else if (!depObj[dep]) depObj[dep] = 'latest';
      });

      result.push({
        path: packageJsonPath,
        content: JSON.stringify({
          name: isMonorepo ? 'client' : componentName.toLowerCase().replace(/\s+/g, '-'),
          version: '0.1.0',
          type: 'module',
          private: isMonorepo ? true : undefined,
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview'
          },
          dependencies: depObj,
          devDependencies: requiredDevDeps
        }, null, 2)
      });
    } else {
      // package.json exists - merge required devDependencies
      try {
        const existingPackageJson = JSON.parse(result[existingPackageJsonIndex].content);

        // Ensure devDependencies object exists
        if (!existingPackageJson.devDependencies) {
          existingPackageJson.devDependencies = {};
        }

        // Merge required devDependencies (our versions take precedence to ensure compatibility)
        Object.assign(existingPackageJson.devDependencies, requiredDevDeps);

        // Ensure dependencies object exists with at least react and react-dom
        if (!existingPackageJson.dependencies) {
          existingPackageJson.dependencies = {};
        }
        if (!existingPackageJson.dependencies.react) {
          existingPackageJson.dependencies.react = '^18.3.1';
        }
        if (!existingPackageJson.dependencies['react-dom']) {
          existingPackageJson.dependencies['react-dom'] = '^18.3.1';
        }

        // Ensure scripts exist
        if (!existingPackageJson.scripts) {
          existingPackageJson.scripts = {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview'
          };
        }

        // Ensure type module is set
        existingPackageJson.type = 'module';

        // Update the package.json in the result
        result[existingPackageJsonIndex].content = JSON.stringify(existingPackageJson, null, 2);

        this.logger.info('AICodeGenerator', 'Merged required devDependencies into AI-generated package.json', {
          addedDeps: Object.keys(requiredDevDeps)
        });
      } catch (error) {
        this.logger.error('AICodeGenerator', 'Failed to parse existing package.json, replacing it', { error });
        // If parsing fails, replace with our own
        const depObj: Record<string, string> = {
          'react': '^18.3.1',
          'react-dom': '^18.3.1',
        };
        dependencies.forEach(dep => {
          if (dep === 'framer-motion') depObj[dep] = '^11.13.1';
          else if (dep === 'lucide-react') depObj[dep] = '^0.453.0';
          else if (dep === 'clsx') depObj[dep] = '^2.1.1';
          else if (dep === 'tailwind-merge') depObj[dep] = '^2.5.4';
          else if (dep === 'date-fns') depObj[dep] = '^3.6.0';
          else if (dep === 'recharts') depObj[dep] = '^2.13.0';
          else if (dep === 'react-hook-form') depObj[dep] = '^7.53.1';
          else if (dep === 'zod') depObj[dep] = '^3.25.76';
          else if (dep === 'react-router-dom') depObj[dep] = '^6.26.0';
          else if (!depObj[dep]) depObj[dep] = 'latest';
        });

        result[existingPackageJsonIndex].content = JSON.stringify({
          name: componentName.toLowerCase().replace(/\s+/g, '-'),
          version: '0.1.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview'
          },
          dependencies: depObj,
          devDependencies: requiredDevDeps
        }, null, 2);
      }
    }

    // Ensure index.html (in client/ for monorepo, root for single-package)
    const indexHtmlPath = isMonorepo ? 'client/index.html' : 'index.html';
    if (!existingPaths.has(indexHtmlPath) && !existingPaths.has('index.html')) {
      result.push({
        path: indexHtmlPath,
        content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${componentName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`
      });
      this.logger.info('AICodeGenerator', 'Created fallback index.html without CSP restrictions');
    }

    // Ensure vite.config.ts (in client/ for monorepo, root for single-package)
    const viteConfigPath = isMonorepo ? 'client/vite.config.ts' : 'vite.config.ts';
    if (!existingPaths.has(viteConfigPath) && !existingPaths.has('vite.config.ts')) {
      result.push({
        path: viteConfigPath,
        content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    host: true
  },
  build: {
    outDir: 'dist',
    sourcemap: true
  }
});`
      });
    }

    // Ensure tsconfig.node.json FIRST (required by vite.config.ts and referenced by tsconfig.json)
    if (!existingPaths.has('tsconfig.node.json')) {
      result.push({
        path: 'tsconfig.node.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2022',
            lib: ['ES2023'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowSyntheticDefaultImports: true,
            strict: true,
            resolveJsonModule: true,
            isolatedModules: true,
            moduleDetection: 'force',
            noEmit: true
          },
          include: ['vite.config.ts']
        }, null, 2)
      });
    }

    // Ensure tsconfig.json (may reference tsconfig.node.json)
    const existingTsConfigIndex = result.findIndex(f => f.path === 'tsconfig.json');
    if (existingTsConfigIndex === -1) {
      // Create new tsconfig.json without references (simpler, works without tsconfig.node.json)
      result.push({
        path: 'tsconfig.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2020',
            useDefineForClassFields: true,
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowImportingTsExtensions: true,
            isolatedModules: true,
            moduleDetection: 'force',
            noEmit: true,
            jsx: 'react-jsx',
            strict: true,
            noUnusedLocals: true,
            noUnusedParameters: true,
            noFallthroughCasesInSwitch: true,
            noUncheckedSideEffectImports: true
          },
          include: ['src']
        }, null, 2)
      });
    } else {
      // AI-generated tsconfig.json exists - ensure it doesn't reference tsconfig.node.json if file doesn't exist
      try {
        const tsConfig = JSON.parse(result[existingTsConfigIndex].content);
        // If references exist but tsconfig.node.json doesn't exist, remove references
        if (tsConfig.references && !existingPaths.has('tsconfig.node.json')) {
          delete tsConfig.references;
          result[existingTsConfigIndex].content = JSON.stringify(tsConfig, null, 2);
          this.logger.info('AICodeGenerator', 'Removed references from tsconfig.json (tsconfig.node.json not found)');
        }
      } catch (error) {
        // If parsing fails, replace with our own
        this.logger.warning('AICodeGenerator', 'Failed to parse AI-generated tsconfig.json, replacing it', { error });
        result[existingTsConfigIndex] = {
          path: 'tsconfig.json',
          content: JSON.stringify({
            compilerOptions: {
              target: 'ES2020',
              useDefineForClassFields: true,
              lib: ['ES2020', 'DOM', 'DOM.Iterable'],
              module: 'ESNext',
              skipLibCheck: true,
              moduleResolution: 'bundler',
              allowImportingTsExtensions: true,
              isolatedModules: true,
              moduleDetection: 'force',
              noEmit: true,
              jsx: 'react-jsx',
              strict: true,
              noUnusedLocals: true,
              noUnusedParameters: true,
              noFallthroughCasesInSwitch: true,
              noUncheckedSideEffectImports: true
            },
            include: ['src']
          }, null, 2)
        };
      }
    }

    // Ensure tailwind.config.js
    if (!existingPaths.has('tailwind.config.js')) {
      result.push({
        path: 'tailwind.config.js',
        content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
      });
    }

    // Ensure postcss.config.js
    if (!existingPaths.has('postcss.config.js')) {
      result.push({
        path: 'postcss.config.js',
        content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
      });
    }

    // Ensure src/main.tsx if not present (client/src/main.tsx for monorepo, src/main.tsx for single-package)
    const mainTsxPath = isMonorepo ? 'client/src/main.tsx' : 'src/main.tsx';
    if (!existingPaths.has(mainTsxPath) && !existingPaths.has('src/main.tsx') && !existingPaths.has('client/src/main.tsx')) {
      result.push({
        path: mainTsxPath,
        content: `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);`
      });
    }

    // Ensure src/index.css if not present (client/src/index.css for monorepo, src/index.css for single-package)
    const indexCssPath = isMonorepo ? 'client/src/index.css' : 'src/index.css';
    if (!existingPaths.has(indexCssPath) && !existingPaths.has('src/index.css') && !existingPaths.has('client/src/index.css')) {
      result.push({
        path: indexCssPath,
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}`
      });
    }

    // 🚨 CRITICAL: Ensure src/App.tsx ALWAYS exists (main.tsx imports it)
    // client/src/App.tsx for monorepo, src/App.tsx for single-package
    const appTsxPath = isMonorepo ? 'client/src/App.tsx' : 'src/App.tsx';
    if (!existingPaths.has(appTsxPath) && !existingPaths.has('src/App.tsx') && !existingPaths.has('client/src/App.tsx')) {
      this.logger.warning('AICodeGenerator', 'AI did not generate src/App.tsx - creating fallback', {
        componentName
      });

      result.push({
        path: appTsxPath,
        content: `// Main application component
export default function App() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
      <div className="max-w-2xl w-full bg-white rounded-2xl shadow-xl p-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          ${componentName}
        </h1>
        <p className="text-lg text-gray-600 mb-6">
          Welcome to your new application! This is a starter template.
        </p>
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <p className="text-sm text-blue-800">
            💡 <strong>Next steps:</strong> Customize this component to build your application.
          </p>
        </div>
      </div>
    </div>
  );
}`
      });
      existingPaths.add(appTsxPath);
    }

    this.logger.info('AICodeGenerator', `Ensured all required files. Total files: ${result.length}`, {
      addedFiles: result.length - files.length
    });

    return result;
  }

  /**
   * Sanitizes CSS files to remove undefined CSS variable patterns
   * These patterns (border-border, bg-background, text-foreground) are shadcn/ui
   * patterns that require CSS variable definitions. Without them, Tailwind fails.
   */
  private sanitizeCSSFiles(files: { path: string; content: string }[]): { path: string; content: string }[] {
    return files.map(file => {
      // Only process CSS files
      if (!file.path.endsWith('.css')) {
        return file;
      }

      let content = file.content;
      let modified = false;

      // Problematic patterns that require CSS variables
      const problematicPatterns = [
        // border-* patterns
        /@apply\s+border-border\s*;?/g,
        /@apply\s+border-input\s*;?/g,
        // background patterns
        /@apply\s+bg-background\s*;?/g,
        /@apply\s+bg-card\s*;?/g,
        /@apply\s+bg-muted\s*;?/g,
        /@apply\s+bg-primary\s*;?/g,
        /@apply\s+bg-secondary\s*;?/g,
        /@apply\s+bg-destructive\s*;?/g,
        /@apply\s+bg-popover\s*;?/g,
        /@apply\s+bg-accent\s*;?/g,
        // text patterns
        /@apply\s+text-foreground\s*;?/g,
        /@apply\s+text-card-foreground\s*;?/g,
        /@apply\s+text-muted-foreground\s*;?/g,
        /@apply\s+text-primary-foreground\s*;?/g,
        /@apply\s+text-secondary-foreground\s*;?/g,
        /@apply\s+text-destructive-foreground\s*;?/g,
        /@apply\s+text-popover-foreground\s*;?/g,
        /@apply\s+text-accent-foreground\s*;?/g,
        // ring patterns
        /@apply\s+ring-ring\s*;?/g,
      ];

      // Remove problematic patterns
      for (const pattern of problematicPatterns) {
        if (pattern.test(content)) {
          content = content.replace(pattern, '');
          modified = true;
        }
      }

      // Also check for combined @apply statements with these classes
      const combinedApplyPattern = /@apply\s+([^;]+);/g;
      content = content.replace(combinedApplyPattern, (match, classes) => {
        const problematicClasses = [
          'border-border', 'border-input',
          'bg-background', 'bg-card', 'bg-muted', 'bg-primary', 'bg-secondary', 
          'bg-destructive', 'bg-popover', 'bg-accent',
          'text-foreground', 'text-card-foreground', 'text-muted-foreground',
          'text-primary-foreground', 'text-secondary-foreground', 
          'text-destructive-foreground', 'text-popover-foreground', 'text-accent-foreground',
          'ring-ring'
        ];
        
        const classArray = classes.split(/\s+/).filter((c: string) => c.trim());
        const filteredClasses = classArray.filter((c: string) => !problematicClasses.includes(c));
        
        if (filteredClasses.length !== classArray.length) {
          modified = true;
          if (filteredClasses.length === 0) {
            return ''; // Remove entire @apply if no classes left
          }
          return `@apply ${filteredClasses.join(' ')};`;
        }
        return match;
      });

      // Clean up empty @layer blocks that might result
      content = content.replace(/@layer\s+base\s*\{\s*\*\s*\{\s*\}\s*\}/g, '');
      content = content.replace(/@layer\s+base\s*\{\s*body\s*\{\s*\}\s*\}/g, '');
      
      // Clean up empty rule blocks
      content = content.replace(/\*\s*\{\s*\}/g, '');
      content = content.replace(/body\s*\{\s*\}/g, '');
      
      // Clean up multiple newlines
      content = content.replace(/\n{3,}/g, '\n\n');

      if (modified) {
        this.logger.info('AICodeGenerator', `Sanitized CSS file ${file.path} - removed undefined CSS variable patterns`);
      }

      return { path: file.path, content };
    });
  }

  /**
   * Sanitizes Timer/Counter code to prevent NaN display issues
   * Common patterns that cause NaN: uninitialized useState, unsafe time formatting
   */
  private sanitizeTimerCode(files: { path: string; content: string }[]): { path: string; content: string }[] {
    return files.map(file => {
      // Only process TypeScript/JavaScript files
      if (!file.path.match(/\.(tsx?|jsx?)$/)) {
        return file;
      }

      let content = file.content;
      let modified = false;

      // Fix: useState() without initial value for numbers
      // Pattern: useState() or useState<number>() -> useState(0)
      const uninitializedUseState = /useState<number>\s*\(\s*\)/g;
      if (uninitializedUseState.test(content)) {
        content = content.replace(uninitializedUseState, 'useState<number>(0)');
        modified = true;
      }

      // Fix: Time formatting that doesn't handle undefined/NaN
      // Add safety checks to common time formatting patterns
      
      // Pattern: Math.floor(something / 60) without safety
      const unsafeMinutes = /Math\.floor\(\s*(\w+)\s*\/\s*60\s*\)/g;
      if (unsafeMinutes.test(content) && content.includes('NaN')) {
        // Only fix if NaN is actually a potential issue
        // This is a conservative fix
      }

      // Fix: Direct template literal time display without guards
      // Pattern: ${minutes}:${seconds} -> ${minutes ?? 0}:${seconds ?? 0}
      const unsafeTimeDisplay = /\$\{(\w+)\}:\$\{(\w+)\}/g;
      const matches = content.match(unsafeTimeDisplay);
      if (matches) {
        for (const match of matches) {
          // Extract variable names
          const parts = match.match(/\$\{(\w+)\}:\$\{(\w+)\}/);
          if (parts && (parts[1].includes('min') || parts[1].includes('sec') || 
                        parts[2].includes('min') || parts[2].includes('sec') ||
                        parts[1].includes('hour') || parts[2].includes('hour'))) {
            const safeVersion = `\${String(${parts[1]} ?? 0).padStart(2, '0')}:\${String(${parts[2]} ?? 0).padStart(2, '0')}`;
            content = content.replace(match, safeVersion);
            modified = true;
          }
        }
      }

      // Fix: formatTime functions without NaN guards
      // If a file contains formatTime and shows a potential NaN pattern, add guards
      if (content.includes('formatTime') && content.includes('return `') && 
          !content.includes('?? 0') && !content.includes('isNaN')) {
        // Add NaN guard comment to remind about safe formatting
        // This is documentation-based as complex AST transformation is risky
      }

      if (modified) {
        this.logger.info('AICodeGenerator', `Sanitized timer code in ${file.path} - added NaN safety guards`);
      }

      return { path: file.path, content };
    });
  }

  /**
   * Validates all imports in generated files and creates missing files
   * This fixes the issue where AI generates imports but not the actual files
   */
  private validateAndFixImports(files: { path: string; content: string }[]): { path: string; content: string }[] {
    const result = [...files];
    const existingPaths = new Set(files.map(f => f.path));
    const missingFiles = new Map<string, string[]>(); // path -> [files that import it]

    // Extract all imports from all files
    for (const file of files) {
      const imports = this.extractLocalImports(file.content);

      for (const importPath of imports) {
        // Convert relative import to absolute path
        const absolutePath = this.resolveImportPath(file.path, importPath);

        if (absolutePath && !existingPaths.has(absolutePath)) {
          if (!missingFiles.has(absolutePath)) {
            missingFiles.set(absolutePath, []);
          }
          missingFiles.get(absolutePath)!.push(file.path);
        }
      }
    }

    // Create stub files for missing imports
    if (missingFiles.size > 0) {
      this.logger.warning('AICodeGenerator', `Found ${missingFiles.size} missing imported files, creating stubs`, {
        missingFiles: Array.from(missingFiles.keys())
      });

      for (const [missingPath, importers] of missingFiles.entries()) {
        const stubContent = this.createStubFile(missingPath, importers);
        result.push({
          path: missingPath,
          content: stubContent
        });
        existingPaths.add(missingPath);
      }
    }

    return result;
  }

  /**
   * Extract local import paths from TypeScript/JavaScript code
   */
  private extractLocalImports(content: string): string[] {
    const imports: string[] = [];

    // Match: import ... from './path' or import ... from '../path'
    const importRegex = /import\s+(?:{[^}]+}|[^'\s]+|\*\s+as\s+[^\s]+)\s+from\s+['"](\.\/.+?|\.\.?\/.+?)['"];?/g;

    let match;
    while ((match = importRegex.exec(content)) !== null) {
      imports.push(match[1]);
    }

    return imports;
  }

  /**
   * Resolve relative import path to absolute file path
   */
  private resolveImportPath(fromFile: string, importPath: string): string | null {
    // Get directory of the importing file
    const fromDir = fromFile.substring(0, fromFile.lastIndexOf('/'));

    // Handle different import patterns
    let targetPath = importPath;

    // Remove leading './' or '../'
    const parts = importPath.split('/');
    let currentDir = fromDir;

    for (const part of parts) {
      if (part === '..') {
        // Go up one directory
        const lastSlash = currentDir.lastIndexOf('/');
        currentDir = lastSlash > 0 ? currentDir.substring(0, lastSlash) : '';
      } else if (part === '.') {
        // Stay in current directory
        continue;
      } else {
        // Add to path
        currentDir = currentDir ? `${currentDir}/${part}` : part;
      }
    }

    // Check if path already has a valid extension
    if (currentDir.match(/\.(tsx?|jsx?|js|css|json)$/)) {
      return currentDir;
    }

    // Try adding extensions
    const possibleExtensions = ['.tsx', '.ts', '.jsx', '.js', '/index.tsx', '/index.ts'];

    for (const ext of possibleExtensions) {
      const testPath = currentDir + ext;
      if (!testPath.includes('..')) {
        return testPath;
      }
    }

    // If no extension and no index, default to .tsx
    return currentDir + '.tsx';
  }

  /**
   * Create a stub file for a missing import
   */
  private createStubFile(path: string, importedBy: string[]): string {
    // 🚨 CRITICAL: Handle CSS files
    if (path.endsWith('.css') || path.endsWith('.scss') || path.endsWith('.less')) {
      const fileName = path.substring(path.lastIndexOf('/') + 1).replace(/\.(css|scss|less)$/, '');
      const componentName = fileName.charAt(0).toUpperCase() + fileName.slice(1).replace(/[-_]/g, '');
      return `/* Auto-generated CSS file for ${componentName} component */
/* This file was automatically created because it was imported but missing */
/* Imported by: ${importedBy.join(', ')} */

.${fileName.toLowerCase().replace(/[-_]/g, '-')} {
  /* Add your styles here */
}
`;
    }
    
    const fileName = path.substring(path.lastIndexOf('/') + 1).replace(/\.(tsx?|jsx?)$/, '');
    const isComponent = path.includes('/components/') || fileName.charAt(0) === fileName.charAt(0).toUpperCase();
    const isType = path.includes('/types/') || path.endsWith('types.ts');
    const isHook = path.includes('/hooks/') || fileName.startsWith('use');
    const isUtil = path.includes('/utils/') || path.includes('/lib/');
    const isContext = path.includes('/context/');

    if (isType) {
      // Create type definition file
      return `// Type definitions
// Auto-generated stub - imported by: ${importedBy.join(', ')}

export interface ${fileName.replace(/[-_]/g, '')} {
  id: string | number;
  [key: string]: any;
}

export type ${fileName}Type = ${fileName.replace(/[-_]/g, '')};
`;
    }

    if (isContext) {
      // Create context file (React 18+ JSX transform)
      return `import { createContext, useContext, ReactNode } from 'react';

// Auto-generated stub - imported by: ${importedBy.join(', ')}

interface ${fileName}ContextType {
  // Add your context properties here
  value: any;
}

const ${fileName}Context = createContext<${fileName}ContextType | undefined>(undefined);

export function ${fileName}Provider({ children }: { children: ReactNode }) {
  const value = {
    value: null
  };

  return (
    <${fileName}Context.Provider value={value}>
      {children}
    </${fileName}Context.Provider>
  );
}

export function use${fileName}() {
  const context = useContext(${fileName}Context);
  if (context === undefined) {
    throw new Error('use${fileName} must be used within a ${fileName}Provider');
  }
  return context;
}
`;
    }

    if (isHook) {
      // Create custom hook file
      return `import { useState } from 'react';

// Auto-generated stub - imported by: ${importedBy.join(', ')}

export const ${fileName} = () => {
  const [state, setState] = useState<any>(null);

  return {
    state,
    setState
  };
};
`;
    }

    if (isUtil) {
      // Create utility file
      return `// Utility functions
// Auto-generated stub - imported by: ${importedBy.join(', ')}

export const ${fileName.replace(/[-_]/g, '')} = (input: any): any => {
  return input;
};

export default ${fileName.replace(/[-_]/g, '')};
`;
    }

    if (isComponent) {
      // Create React component file (React 18+ JSX transform - no React import needed)
      // Use NAMED export for components in src/components/ to match import patterns
      return `// Auto-generated stub - imported by: ${importedBy.join(', ')}

interface ${fileName}Props {
  [key: string]: any;
}

export function ${fileName}(props: ${fileName}Props) {
  return (
    <div className="p-4">
      <h2 className="text-xl font-semibold">${fileName}</h2>
      <p className="text-gray-600">This component is under development.</p>
    </div>
  );
}

// Named export only - do NOT use default export for components in src/components/
`;
    }

    // Default: Create a simple module
    return `// Auto-generated module
// Imported by: ${importedBy.join(', ')}

export const placeholder = true;

export default {};
`;
  }

  async generateHooks(componentName: string, features: string[]): Promise<string> {
    try {
      const systemPrompt = `You are an expert React developer. Generate custom hooks for a React component.

Create TypeScript custom hooks that would be useful for a "${componentName}" component with these features: ${features.join(', ')}.

Return ONLY the hook code, no explanations.`;

      const userPrompt = `Generate useful custom hooks for the ${componentName} component. Focus on hooks that would be commonly used with these features: ${features.join(', ')}.`;

      const response = await this.anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 2000,
        temperature: 0.7,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      });

      return response.content[0]?.type === 'text' ? response.content[0].text : '';
    } catch (error) {
      this.logger.error('AICodeGenerator', 'Failed to generate hooks', { error });
      return '';
    }
  }

  async generateTypes(componentName: string, features: string[]): Promise<string> {
    try {
      const systemPrompt = `You are an expert TypeScript developer. Generate TypeScript type definitions for a React component.

Create comprehensive TypeScript interfaces and types for a "${componentName}" component with these features: ${features.join(', ')}.

Return ONLY the TypeScript type definitions, no explanations.`;

      const userPrompt = `Generate TypeScript types and interfaces for the ${componentName} component. Include all necessary types for the features: ${features.join(', ')}.`;

      const response = await this.anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 1500,
        temperature: 0.7,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      });

      return response.content[0]?.type === 'text' ? response.content[0].text : '';
    } catch (error) {
      this.logger.error('AICodeGenerator', 'Failed to generate types', { error });
      return '';
    }
  }

}

// Export singleton instance
export const aiCodeGenerator = new AICodeGenerator();
