import Anthropic from '@anthropic-ai/sdk';
import { Logger } from '../utils/Logger';
import { RateLimiter } from '../utils/RateLimiter';
import { multiModelAI, AIRequest } from './MultiModelAIService';

export interface AIGenerationRequest {
  prompt: string;
  componentName: string;
  features: string[];
  styling?: {
    animations: boolean;
    theme: string;
  };
  context?: string;
  modelPreference?: 'speed' | 'quality' | 'cost';
  provider?: 'anthropic' | 'openai' | 'gemini' | 'auto';
  orchestrated?: boolean; // If true, skip internal prompt building (orchestrator already built prompts)
  systemPrompt?: string; // Optional pre-built system prompt from orchestrator
}

export interface AIGenerationResponse {
  success: boolean;
  code?: string; // Main component code (for backwards compatibility)
  files?: { path: string; content: string }[]; // Multi-file support
  dependencies: string[];
  error?: string;
  warning?: string; // For non-fatal issues like parsing fallbacks
  parseWarning?: string; // Specific warning about file parsing
  metadata?: {
    provider: string;
    model: string;
    responseTime: number;
    tokens: number;
    cost: number;
    parsingMethod?: 'json' | 'markdown' | 'fallback';
  };
}

export class AICodeGenerator {
  private anthropic: Anthropic;
  private logger: Logger;
  private limiter: RateLimiter;

  constructor() {
    this.anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
    this.logger = new Logger(process.cwd());
    this.logger.initialize().catch(console.error);
    this.limiter = new RateLimiter(5);
  }

  async generateComponent(request: AIGenerationRequest): Promise<AIGenerationResponse> {
    try {
      console.log('🎨 AICodeGenerator: Starting component generation');
      console.log('📝 AICodeGenerator: Request:', {
        componentName: request.componentName,
        features: request.features,
        promptLength: request.prompt.length,
        orchestrated: request.orchestrated || false
      });

      this.logger.info('AICodeGenerator', 'Generating component with multi-model AI', {
        componentName: request.componentName,
        features: request.features,
        provider: request.provider || 'auto',
        preference: request.modelPreference || 'quality',
        orchestrated: request.orchestrated || false
      });

      let systemPrompt: string;
      let userPrompt: string;

      if (request.orchestrated) {
        // PASS-THROUGH MODE: Orchestrator already built comprehensive prompts
        // Use them directly to avoid double-prompting confusion
        console.log('🎯 AICodeGenerator: ORCHESTRATED MODE - Using pre-built prompts');
        systemPrompt = request.systemPrompt || '';
        userPrompt = request.prompt; // Use orchestrator's prompt exactly as-is
        console.log('📊 AICodeGenerator: Orchestrated prompt sizes:', {
          system: systemPrompt.length,
          user: userPrompt.length
        });
      } else {
        // LEGACY MODE: Build prompts internally (for direct calls not from orchestrator)
        console.log('🏗️ AICodeGenerator: LEGACY MODE - Building prompts internally');
        systemPrompt = this.buildSystemPromptMultiFile(request);
        userPrompt = this.buildUserPromptMultiFile(request);
        console.log('📊 AICodeGenerator: Built prompt sizes:', {
          system: systemPrompt.length,
          user: userPrompt.length
        });
      }

      // Use multi-model AI service
      const aiRequest: AIRequest = {
        prompt: userPrompt,
        systemPrompt,
        maxTokens: 8000,
        temperature: 0.7,
        useCase: 'code_generation',
        priority: request.modelPreference || 'quality'
      };

      console.log('🤖 AICodeGenerator: Calling multiModelAI.generate()...');
      const startTime = Date.now();
      const response = await multiModelAI.generate(aiRequest);
      const elapsed = Date.now() - startTime;
      console.log(`✅ AICodeGenerator: multiModelAI.generate() completed in ${elapsed}ms`);

      if (!response.content) {
        throw new Error('No code generated by AI');
      }

      // Debug: Log response preview for troubleshooting
      console.error('=== AI RESPONSE DEBUG START ===');
      console.error(`Total length: ${response.content.length} chars`);
      console.error(`Starts with [: ${response.content.trim().startsWith('[')}`);
      console.error(`Ends with ]: ${response.content.trim().endsWith(']')}`);
      console.error(`Contains markdown: ${response.content.includes('```')}`);
      console.error('--- FIRST 1000 CHARS ---');
      console.error(response.content.substring(0, 1000));
      console.error('--- LAST 1000 CHARS ---');
      console.error(response.content.substring(Math.max(0, response.content.length - 1000)));
      console.error('=== AI RESPONSE DEBUG END ===');

      // Parse the multi-file JSON response
      const parseResult = this.parseMultiFileResponse(response.content);

      if (parseResult.files.length === 0) {
        throw new Error('AI generated no files');
      }

      // STEP 1: Fix syntax issues FIRST (before validation)
      // This ensures patterns like "return (;" get fixed before validation throws errors
      console.log('🔧 Applying automatic syntax fixes to generated code...');
      parseResult.files = this.autoFixCommonSyntaxIssues(parseResult.files);
      console.log('✅ Syntax fixes applied');

      // STEP 2: THEN validate that files don't contain JSON structures
      console.log('🔍 Validating file contents...');
      parseResult.files = parseResult.files.map(file => {
        const trimmed = file.content.trim();

        // IMPROVED: More precise JSON-inside-JSON detection
        // Only flag if it looks like the ENTIRE file is our multi-file JSON structure
        // Not just TypeScript code that happens to have "path" or "content" fields

        // Pattern 1: File is a JSON array like: [{"path": "...", "content": "..."}]
        const looksLikeFileArray = trimmed.startsWith('[') &&
          /^\s*\[\s*\{\s*"path"\s*:\s*"[^"]+"\s*,\s*"content"\s*:/.test(trimmed) &&
          trimmed.endsWith(']');

        // Pattern 2: File is a single JSON object like: {"path": "...", "content": "..."}
        const looksLikeSingleFileObject = /^\s*\{\s*"path"\s*:\s*"[^"]+"\s*,\s*"content"\s*:\s*"/.test(trimmed) &&
          !trimmed.includes('export') && // TypeScript exports are NOT JSON
          !trimmed.includes('interface') && // TypeScript interfaces are NOT JSON
          !trimmed.includes('type') && // TypeScript types are NOT JSON
          !trimmed.includes('import'); // TypeScript imports are NOT JSON

        if (looksLikeFileArray || looksLikeSingleFileObject) {
          console.error(`❌ CRITICAL ERROR: ${file.path} contains JSON structure instead of code!`);
          console.error(`First 500 chars: ${trimmed.substring(0, 500)}`);

          // Try to extract the actual code if it's nested JSON
          try {
            const parsed = JSON.parse(trimmed);
            if (Array.isArray(parsed) && parsed[0]?.path && parsed[0]?.content) {
              // This is the entire JSON array embedded in a file - extract the matching file
              const match = parsed.find((f: any) => f.path === file.path);
              if (match?.content) {
                console.log(`✅ Recovered actual content for ${file.path} from nested JSON`);
                return { ...file, content: match.content };
              }
            } else if (parsed.content && typeof parsed.content === 'string') {
              // Single file JSON object
              console.log(`✅ Recovered actual content for ${file.path} from JSON wrapper`);
              return { ...file, content: parsed.content };
            }
          } catch (e) {
            console.error(`Failed to recover content from malformed JSON in ${file.path}`);
          }

          throw new Error(`CRITICAL: ${file.path} contains JSON metadata instead of actual code. The AI generated malformed output.`);
        }
        return file;
      });
      console.log('✅ File validation passed');

      // Extract all dependencies from all files
      const dependencies = this.extractDependenciesFromFiles(parseResult.files);

      this.logger.info('AICodeGenerator', 'Multi-file component generated successfully', {
        filesCount: parseResult.files.length,
        dependencies,
        provider: response.provider,
        model: response.model,
        responseTime: response.responseTime,
        cost: response.usage.cost,
        parsingMethod: parseResult.method,
      });

      // Validate and fix missing imports
      const validatedFiles = this.validateAndFixImports(parseResult.files);

      // Ensure all required configuration files are present
      const completeFiles = this.ensureRequiredFiles(validatedFiles, dependencies, request.componentName);

      const result: AIGenerationResponse = {
        success: true,
        files: completeFiles,
        code: completeFiles.find(f => f.path === 'src/App.tsx')?.content || '', // Backwards compatibility
        dependencies,
        metadata: {
          provider: response.provider,
          model: response.model,
          responseTime: response.responseTime,
          tokens: response.usage.totalTokens,
          cost: response.usage.cost,
          parsingMethod: parseResult.method,
        },
      };

      // Add warning if fallback parsing was used
      if (parseResult.warning) {
        result.parseWarning = parseResult.warning;
        result.warning = parseResult.warning;
      }

      return result;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      this.logger.error('AICodeGenerator', 'Failed to generate component', {
        error: errorMessage,
      });

      return {
        success: false,
        code: '',
        files: [],
        dependencies: [],
        error: errorMessage,
      };
    }
  }

  private buildSystemPrompt(request: AIGenerationRequest): string {
    return `You are an expert React developer specializing in creating modern, functional web applications.

Your task is to generate a complete, working React component based on the user's requirements.

CRITICAL REQUIREMENTS:
- Use React 18+ with TypeScript
- Use modern React patterns (hooks, functional components)
- Include proper TypeScript types and interfaces
- Use Tailwind CSS for styling (with inline classes, use modern gradients and shadows)
- Make the component fully functional and interactive with realistic data
- Include proper error handling and loading states

🚨 CRITICAL SYNTAX RULES - VERIFY BEFORE RESPONDING 🚨
ABSOLUTELY NO SYNTAX ERRORS ALLOWED:
❌ NEVER write "return (;" - this is a CRITICAL ERROR
❌ NEVER put semicolons immediately after opening parentheses: (;
❌ NEVER put semicolons immediately after opening braces: {;
❌ NEVER put semicolons immediately after opening brackets: [;
✅ ALWAYS verify your code has valid JavaScript/TypeScript syntax
✅ ALWAYS check that parentheses, braces, and brackets are properly closed
✅ DOUBLE-CHECK every return statement for correct syntax
- Use semantic HTML elements
- Make it responsive and accessible (works on mobile, tablet, desktop)
- Add smooth transitions and professional UI/UX
- Include keyboard navigation and ARIA labels
- Use modern design patterns (cards, modals, toasts, etc.)
- Add data persistence with localStorage where appropriate

🚨 CRITICAL - SINGLE FILE COMPONENT RULE 🚨
This is the MOST IMPORTANT requirement - if you violate this, the app will BREAK:

❌ ABSOLUTELY FORBIDDEN - You MUST NOT do these:
- NO "import ... from './components/...'"
- NO "import ... from './utils/...'"
- NO "import ... from './hooks/...'"
- NO "import ... from './types/...'"
- NO "import ... from './lib/...'"
- NO "import ... from './services/...'"
- NO relative imports starting with "./" or "../"

✅ ALLOWED - You CAN ONLY import from:
- "react" and "react-dom"
- npm packages: "framer-motion", "lucide-react", "clsx", "date-fns", etc.

✅ REQUIRED - Put EVERYTHING in ONE file:
- Define ALL interfaces and types at the top of the file
- Define ALL helper functions in the file
- Define ALL sub-components in the file (before the main component)
- Define ALL utilities in the file
- Define ALL constants in the file
- The ONLY exports should be: "export default function App()"

Example CORRECT structure:
\`\`\`typescript
import React, { useState } from 'react';

// Types
interface Recipe {
  id: number;
  title: string;
}

// Helper functions
const formatDate = (date: Date) => date.toLocaleDateString();

// Sub-components (if needed)
const RecipeCard = ({ recipe }: { recipe: Recipe }) => (
  <div>{recipe.title}</div>
);

// Main component - MUST be named "App"
export default function App() {
  return <div>...</div>;
}
\`\`\`

COMPONENT SPECIFICATIONS:
- Component Name: App (always use "App" as the exported component name)
- Features: ${request.features.join(', ')}
- Theme: ${request.styling?.theme || 'light'}
- Animations: ${request.styling?.animations ? 'Include smooth animations' : 'No animations needed'}

OUTPUT FORMAT:
Return ONLY the complete React component code. Do not include markdown code fences (\`\`\`), explanations, or any other text. Just the raw TypeScript/React code.

The component should be a complete, functional implementation in ONE SINGLE FILE.`;
  }

  private buildUserPrompt(request: AIGenerationRequest): string {
    let prompt = `Create a React component with the following requirements:\n\n`;

    prompt += `DESCRIPTION: ${request.prompt}\n\n`;

    if (request.features.length > 0) {
      prompt += `REQUIRED FEATURES:\n`;
      request.features.forEach(feature => {
        prompt += `- ${feature}\n`;
      });
      prompt += '\n';
    }

    if (request.context) {
      prompt += `ADDITIONAL CONTEXT: ${request.context}\n\n`;
    }

    prompt += `CRITICAL REMINDERS:
- Create a SINGLE, SELF-CONTAINED file
- NO local imports (no "./components/...", no "./utils/...", etc.)
- Put ALL types, sub-components, and helpers IN THE SAME FILE
- Export the main component as: "export default function App()"
- Make it fully functional and production-ready`;

    return prompt;
  }

  private buildSystemPromptMultiFile(request: AIGenerationRequest): string {
    return `# Role
You are an expert React TypeScript developer specializing in creating modern, production-ready web applications.

# Core Principles
**EFFICIENCY FIRST**: Generate ONLY what's necessary. Don't over-engineer or add features not requested.
**QUALITY OVER QUANTITY**: Focus on making the code production-ready, not feature-rich.
**RESPECT CONSTRAINTS**: Work within the given requirements without adding "nice to have" features.

# Your Expertise
- Building scalable React applications with TypeScript
- Creating intuitive user interfaces with modern design patterns
- Implementing efficient state management and data flow
- Writing clean, maintainable, and performant code
- Following React best practices and accessibility standards

# Primary Task
Generate a COMPLETE, MULTI-FILE React TypeScript application based STRICTLY on the user's requirements.
- ✅ DO: Include everything needed to run the app
- ✅ DO: Follow best practices and write production-ready code
- ❌ DON'T: Add extra features not requested
- ❌ DON'T: Over-engineer simple requirements
- ❌ DON'T: Include unnecessary complexity

## Technical Specifications
- **Framework**: React 18+ with TypeScript
- **Styling**: Tailwind CSS with custom design system
- **State**: Modern React patterns (hooks, context when needed)

## 🚨 CRITICAL SYNTAX RULES - VERIFY ALL CODE 🚨
**ABSOLUTELY NO SYNTAX ERRORS ALLOWED:**
❌ NEVER write "return (;" - this is a CRITICAL ERROR
❌ NEVER put semicolons immediately after opening parentheses: (;
❌ NEVER put semicolons immediately after opening braces: {;
❌ NEVER put semicolons immediately after opening brackets: [;
❌ NEVER put semicolons BEFORE closing parentheses in if/while conditions: if (x === 1; ) ← WRONG
❌ NEVER put semicolons inside conditional expressions: if (a || b; ) ← WRONG
✅ CORRECT: if (a || b) { } ← No semicolon in condition
✅ ALWAYS verify ALL code has valid JavaScript/TypeScript syntax
✅ ALWAYS check that ALL parentheses, braces, and brackets are properly closed
✅ DOUBLE-CHECK every return statement for correct syntax before responding
✅ TRIPLE-CHECK that if/while/for conditions do NOT have semicolons inside parentheses
- **Quality**: Production-ready with error handling
- **Accessibility**: WCAG 2.1 AA compliant
- **Performance**: Optimized for fast loading and smooth interactions

# Architecture Requirements

## Required File Structure
You MUST generate ALL necessary files in this structure:

### Core Application
- \`src/App.tsx\` - Main application component with routing and global state
- \`src/main.tsx\` - React 18 entry point with createRoot
- \`src/index.css\` - Global styles and Tailwind configuration

### Component Architecture
- \`src/components/*.tsx\` - UI components (one per file, properly typed)
- \`src/layouts/*.tsx\` - Layout components if needed
- \`src/pages/*.tsx\` - Page components for different routes

### Type Safety & Utils
- \`src/types/index.ts\` - All TypeScript interfaces and types
- \`src/utils/*.ts\` - Pure utility functions and helpers
- \`src/hooks/*.ts\` - Custom React hooks for logic reuse

### Configuration Files
- \`package.json\` - Complete dependency list and scripts
- \`tsconfig.json\` - TypeScript configuration
- \`tailwind.config.js\` - Tailwind CSS configuration
- \`index.html\` - HTML entry point

# Code Quality Standards

## React Best Practices
- Use functional components with proper TypeScript typing
- Implement proper error boundaries and loading states
- Follow React naming conventions (PascalCase for components)
- Use semantic HTML elements for accessibility
- Implement proper form validation and error handling

## React 18+ Modern Patterns (IMPORTANT)
- ✅ DO: Use function declarations: \`export function Component() {}\` or \`export default function App() {}\`
- ✅ DO: Use the new JSX transform - NO need to \`import React from 'react'\`
- ❌ DON'T: Import React unless using React-specific APIs (useState, useEffect, etc. are fine)
- ✅ DO: Import only what you need: \`import { useState, useEffect } from 'react'\`
- ✅ DO: Use \`createRoot\` in main.tsx (already handled in boilerplate)

## TypeScript Excellence
- Define comprehensive interfaces for all data structures
- Use proper generic types where applicable
- Implement strict null checks and proper error types
- Export types for reusability across components

## Syntax Requirements (CRITICAL - CODE MUST COMPILE)
⚠️ YOUR CODE WILL BE VALIDATED - IT MUST BE SYNTACTICALLY CORRECT ⚠️

### Semicolons
- EVERY statement must end with a semicolon (;)
- NEVER put semicolons after opening parentheses: ❌ \`return (;\` ✅ \`return (\`
- NEVER put semicolons before closing parentheses: ❌ \`;)\` ✅ \`)\`
- NO double semicolons: ❌ \`;;\` ✅ \`;\`

### Return Statements
- ALL return statements must be complete and valid
- ✅ CORRECT: \`return (<div>Hello</div>);\`
- ✅ CORRECT: \`return null;\`
- ❌ WRONG: \`return (;\` (stray semicolon)
- ❌ WRONG: \`return (<div>\` (incomplete)

### Imports and Files
- ALL import statements must have corresponding files in your response
- If you import \`'../types'\`, you MUST include \`src/types/index.ts\` in your JSON
- If you import \`'../utils/gameLogic'\`, you MUST include \`src/utils/gameLogic.ts\` in your JSON

### Code Completeness
- NO incomplete code blocks - every function, component, and expression must be complete
- ALL JSX elements must be properly closed
- ALL curly braces \`{}\`, brackets \`[]\`, and parentheses \`()\` must be balanced
- NO placeholder comments like "// rest of implementation" - write the full code

## UI/UX Standards
- Create responsive layouts that work on all devices
- Implement smooth transitions and micro-interactions
- Use consistent spacing, typography, and color schemes
- Ensure keyboard navigation and screen reader support
- Follow modern design patterns (cards, buttons, forms)

# Component Specifications
- **Component Name**: ${request.componentName}
- **Required Features**: ${request.features.join(', ')}
- **Theme**: ${request.styling?.theme || 'light'} mode with proper contrast
- **Animations**: ${request.styling?.animations ? 'Smooth animations with framer-motion' : 'Subtle CSS transitions'}
- **Styling Approach**: Tailwind CSS with custom design tokens

# Critical Output Requirements

## ⚠️⚠️⚠️ CRITICAL: YOU WILL BE PENALIZED IF YOU DON'T FOLLOW THIS FORMAT ⚠️⚠️⚠️

YOUR RESPONSE MUST BE PURE JSON - NO EXCEPTIONS. NO MARKDOWN.

❌ DO NOT include:
- Markdown code blocks (no \`\`\`json or \`\`\`)
- Explanatory text before or after the JSON
- Comments or notes
- Any text that is not part of the JSON structure
- **CRITICAL**: DO NOT put the JSON structure itself inside a "content" field!

✅ DO include:
- ONLY the JSON array starting with [ and ending with ]
- Properly escaped strings (\\n for newlines, \\" for quotes)
- All necessary files in the array
- **CRITICAL**: Each file's "content" must be ACTUAL SOURCE CODE, not more JSON!

## ❌ WRONG - DO NOT DO THIS:
[
  {
    "path": "src/App.tsx",
    "content": "[{\\"path\\":\\"src/components/Grid.tsx\\",\\"content\\":\\"...\\"}]"  ← WRONG! This is JSON inside JSON!
  }
]

## ✅ CORRECT - Required Structure Example

[
  {
    "path": "src/App.tsx",
    "content": "import React from 'react';\\nimport { RecipeForm } from './components/RecipeForm';\\n\\nexport default function App() {\\n  return <RecipeForm />;\\n}"
  },
  {
    "path": "src/components/RecipeForm.tsx",
    "content": "import React from 'react';\\nimport { Recipe } from '../types';\\n\\nexport const RecipeForm = () => {\\n  return <div>Recipe Form</div>;\\n}"
  },
  {
    "path": "src/types/index.ts",
    "content": "export interface Recipe {\\n  id: number;\\n  title: string;\\n}"
  }
]

NOTICE: The "content" field contains ACTUAL TYPESCRIPT/REACT CODE, not JSON metadata!

## Format Verification Checklist
Before responding, verify:
- [ ] Response starts with [
- [ ] Response ends with ]
- [ ] No markdown code blocks (\`\`\`)
- [ ] No explanatory text
- [ ] All newlines escaped as \\n
- [ ] All quotes escaped as \\"
- [ ] Valid JSON that can be parsed

CRITICAL RULES - MUST FOLLOW:
1. Return ONLY the raw JSON array - Your response should be valid JSON that can be directly parsed
2. Every component imported in App.tsx MUST have its own file in the array
3. If App.tsx imports "./components/TaskItem", you MUST include src/components/TaskItem.tsx
4. If App.tsx imports "./components/AddTaskForm", you MUST include src/components/AddTaskForm.tsx
5. Create ALL files for ALL imports - NO EXCEPTIONS
6. Escape newlines as \\n and quotes as \\"
7. Your first character must be [ and your last character must be ]
8. Do not wrap the JSON in any markdown formatting

EFFICIENCY RULES:
- Generate ONLY files that are NECESSARY for the requirements
- DON'T create extra components, hooks, or utilities "just in case"
- DON'T add features not explicitly requested
- Keep the file structure simple and focused on the core requirement
- If the app can work with fewer files, use fewer files

## FINAL SYNTAX CHECKLIST (CHECK EVERY FILE BEFORE RESPONDING):
⚠️ CRITICAL - Your code is being automatically validated. If any of these fail, the entire generation fails:

1. SEMICOLONS: Every statement MUST end with a semicolon
   ✅ CORRECT: return (<div>Hello</div>);
   ❌ WRONG: return (<div>Hello</div>)
   ✅ CORRECT: export const foo = (): string => "bar";
   ❌ WRONG: export const foo = (): string => "bar"

2. IMPORTS MUST HAVE FILES: If you write import X from '../types', you MUST include src/types/index.ts
   Example: If your file has: import { Position } from '../types';
   Then your JSON MUST include: { "path": "src/types/index.ts", "content": "export interface Position {...}" }

3. COMPLETE STATEMENTS: No incomplete or truncated code
   ✅ Every function must have a body
   ✅ Every JSX element must be closed
   ✅ Every brace/bracket/paren must be balanced

4. NO MARKDOWN: First character of your response MUST be [, last character MUST be ]
   ❌ Do NOT start with: \`\`\`json
   ✅ Start with: [

Before you respond, mentally go through EVERY file and check:
- Does every return statement end with semicolon?
- Does every export statement end with semicolon?
- Does every import have a corresponding file in my JSON array?
- Is every JSX element properly closed?`;
  }

  private buildUserPromptMultiFile(request: AIGenerationRequest): string {
    let prompt = `Create a complete React application with the following requirements:\n\n`;

    prompt += `DESCRIPTION: ${request.prompt}\n\n`;

    if (request.features.length > 0) {
      prompt += `REQUIRED FEATURES:\n`;
      request.features.forEach(feature => {
        prompt += `- ${feature}\n`;
      });
      prompt += '\n';
    }

    if (request.context) {
      prompt += `ADDITIONAL CONTEXT: ${request.context}\n\n`;
    }

    prompt += `CRITICAL REMINDERS:
- Generate a COMPLETE file structure
- Create ALL imported components in separate files
- Put types in src/types/index.ts
- Put utilities in src/utils/*.ts
- Put custom hooks in src/hooks/*.ts
- Return the result as a JSON array of files
- Make it production-ready and fully functional`;

    return prompt;
  }

  private parseMultiFileResponse(content: string): {
    files: { path: string; content: string }[];
    method: 'json' | 'markdown' | 'fallback';
    warning?: string;
  } {
    try {
      // Strategy 1: Try to parse as JSON with multiple extraction attempts
      let jsonContent = content.trim();

      // Remove markdown code blocks - be aggressive
      // Handle cases like: ```json\n[...]\n```
      if (jsonContent.includes('```')) {
        // Extract content between first and last ```
        const codeBlockMatch = jsonContent.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
        if (codeBlockMatch && codeBlockMatch[1]) {
          jsonContent = codeBlockMatch[1].trim();
        } else {
          // Fallback: just remove all ``` markers
          jsonContent = jsonContent.replace(/```(?:json)?/g, '').trim();
        }
      }

      // Remove common AI explanatory text before JSON
      jsonContent = jsonContent.replace(/^(?:Here's?|Here is|I've created|I have created|Below is).*?\n/gim, '');

      // Try multiple JSON extraction strategies
      let jsonMatch = null;

      // Strategy 1a: Find JSON array with greedy matching
      jsonMatch = jsonContent.match(/\[\s*\{[\s\S]*\}\s*\]/);

      // Strategy 1b: If that fails, try to find JSON between [ and ]
      if (!jsonMatch) {
        const firstBracket = jsonContent.indexOf('[');
        const lastBracket = jsonContent.lastIndexOf(']');
        if (firstBracket !== -1 && lastBracket !== -1 && lastBracket > firstBracket) {
          jsonMatch = [jsonContent.substring(firstBracket, lastBracket + 1)];
        }
      }

      if (jsonMatch) {
        jsonContent = jsonMatch[0];
      }

      const files = JSON.parse(jsonContent);

      if (!Array.isArray(files)) {
        throw new Error('Response is not an array');
      }

      // Validate each file has path and content
      const validFiles = files.filter(f => f.path && f.content);

      if (validFiles.length === 0) {
        throw new Error('No valid files in JSON response');
      }

      this.logger.info('AICodeGenerator', `Successfully parsed ${validFiles.length} files from JSON`);
      return {
        files: validFiles,
        method: 'json'
      };
    } catch (error) {
      this.logger.warning('AICodeGenerator', 'JSON parsing failed, trying markdown extraction', {
        error: error instanceof Error ? error.message : 'Unknown error'
      });

      // Strategy 2: Try to extract files from markdown code blocks with multiple patterns
      const markdownFiles = this.extractFilesFromMarkdown(content);
      if (markdownFiles.length > 0) {
        this.logger.info('AICodeGenerator', `Extracted ${markdownFiles.length} files from markdown`);
        return {
          files: markdownFiles,
          method: 'markdown',
          warning: `⚠️ File parsing used markdown extraction fallback. The AI response was not in the expected JSON format. Generated ${markdownFiles.length} file(s).`
        };
      }

      // Strategy 3: Try to extract ANY code blocks and infer filenames
      this.logger.warning('AICodeGenerator', 'Trying aggressive code block extraction as last resort');
      const aggressiveFiles = this.extractAnyCodeBlocks(content);
      if (aggressiveFiles.length > 0) {
        this.logger.info('AICodeGenerator', `Extracted ${aggressiveFiles.length} files via aggressive extraction`);
        return {
          files: aggressiveFiles,
          method: 'markdown',
          warning: `⚠️ Used aggressive code extraction. File names may not be accurate. Generated ${aggressiveFiles.length} file(s).`
        };
      }

      // Strategy 4: Last resort - return as single file with imports removed
      this.logger.error('AICodeGenerator', '❌ All parsing strategies failed, falling back to single file', {
        contentSample: content.substring(0, 500)
      });

      // Remove local imports from the content
      const cleanedContent = this.stripLocalImports(content);

      return {
        files: [{
          path: 'src/App.tsx',
          content: cleanedContent
        }],
        method: 'fallback',
        warning: `⚠️ CRITICAL: Failed to parse multi-file structure. The AI response could not be properly parsed as JSON or markdown.

All code has been combined into a single file (src/App.tsx) with local imports removed. This may result in a non-functional application.

Suggestions to fix:
1. Try regenerating with a more specific prompt
2. Ask for "a complete multi-file React application with separate component files"
3. Specify the exact file structure you want
4. Consider using orchestration mode for complex applications`
      };
    }
  }

  /**
   * Aggressive extraction - try to extract any code blocks and infer filenames
   */
  private extractAnyCodeBlocks(content: string): { path: string; content: string }[] {
    const files: { path: string; content: string }[] = [];

    // Extract all code blocks
    const codeBlockPattern = /```(?:typescript|tsx|javascript|jsx|ts|js)?\s*([\s\S]*?)```/gi;
    let match;
    let blockIndex = 0;

    while ((match = codeBlockPattern.exec(content)) !== null) {
      const code = match[1].trim();

      if (code.length < 20) continue; // Skip tiny blocks

      // Try to infer filename from code content
      let filename = `src/Component${blockIndex}.tsx`;

      // Check if it's a component
      if (code.includes('export default function') || code.includes('export const')) {
        const componentMatch = code.match(/(?:export default function|export const)\s+([A-Z]\w+)/);
        if (componentMatch) {
          filename = `src/components/${componentMatch[1]}.tsx`;
        }
      }
      // Check if it's App.tsx
      else if (code.includes('function App') || code.includes('const App')) {
        filename = 'src/App.tsx';
      }
      // Check if it's types
      else if (code.includes('export interface') || code.includes('export type')) {
        filename = 'src/types/index.ts';
      }
      // Check if it's CSS
      else if (code.includes('@tailwind') || code.includes('.css')) {
        filename = 'src/index.css';
      }
      // Check if it's config
      else if (code.includes('export default {') && (code.includes('plugins') || code.includes('theme'))) {
        filename = 'tailwind.config.js';
      }
      else if (code.includes('"name"') && code.includes('"dependencies"')) {
        filename = 'package.json';
      }

      files.push({ path: filename, content: code });
      blockIndex++;
    }

    return files;
  }

  private extractFilesFromMarkdown(content: string): { path: string; content: string }[] {
    const files: { path: string; content: string }[] = [];

    // Try multiple markdown patterns to be more flexible

    // Pattern 1: **filename** or **path/filename** followed by code block
    const pattern1 = /\*\*\s*([^\s*\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs))\s*\*\*[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    // Pattern 2: ### filename or ## filename (markdown heading) followed by code block
    const pattern2 = /(?:^|\n)#{1,4}\s+([^\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs))[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    // Pattern 3: Filename: or File: filename followed by code block (more lenient)
    const pattern3 = /(?:File(?:name)?|Path):\s*(?:`([^`]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs))`|([^\s\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs)))[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    // Pattern 4: Just code blocks with comments indicating filename
    const pattern4 = /```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)\s*(?:\/\/|\/\*)\s*([^\s\n]+\.(?:tsx?|jsx?|css|json|html|js|config\.(?:ts|js)|mjs|cjs)).*?\n([\s\S]*?)```/gi;

    // Pattern 5: Catch-all - any line with a file path followed by a code block (most lenient)
    const pattern5 = /([^\s\n]+\.(?:tsx?|jsx?|css|json|html|js))[\s\n]*```(?:typescript|javascript|tsx|jsx|css|json|html|ts|js)?\s*([\s\S]*?)```/gi;

    const patterns = [pattern1, pattern2, pattern3, pattern4, pattern5];

    for (const pattern of patterns) {
      let match;
      while ((match = pattern.exec(content)) !== null) {
        // Different patterns have groups in different positions
        let path: string;
        let fileContent: string;

        if (pattern === pattern3) {
          // Pattern 3 has optional backticks around path
          path = (match[1] || match[2]).trim();
          fileContent = match[3].trim();
        } else {
          path = match[1].trim();
          fileContent = match[2].trim();
        }

        // Clean up the path - remove any markdown formatting
        path = path.replace(/[*_`]/g, '');

        // Skip if we already have this file or if path/content is invalid
        if (!files.find(f => f.path === path) && path && fileContent && fileContent.length > 10) {
          // Validate extracted content for obvious truncation issues
          const validationWarnings = this.validateExtractedCode(fileContent, path);
          if (validationWarnings.length > 0) {
            console.warn(`⚠️  Markdown extraction warnings for ${path}:`);
            validationWarnings.forEach(w => console.warn(`   - ${w}`));
          }

          files.push({ path, content: fileContent });
        }
      }
    }

    this.logger.info('AICodeGenerator', `extractFilesFromMarkdown found ${files.length} files`, {
      filePaths: files.map(f => f.path)
    });

    return files;
  }

  /**
   * Automatically fix common syntax issues that AI consistently makes
   */
  private autoFixCommonSyntaxIssues(files: { path: string; content: string }[]): { path: string; content: string }[] {
    return files.map(file => {
      // Only fix TypeScript/JavaScript files
      if (!file.path.match(/\.(tsx?|jsx?)$/)) {
        return file;
      }

      let content = file.content;
      let fixesApplied = 0;

      this.logger.info('AICodeGenerator', `🔧 [SYNTAX FIX] Checking ${file.path}...`);
      console.log(`🔧 [SYNTAX FIX] Checking ${file.path} (${content.length} chars)`);

      // ULTRA-CRITICAL FIX: Detect and log if we find the problematic patterns BEFORE fixing
      const criticalPatterns = [
        { name: 'return (;', regex: /return\s*\(\s*;/g },
        { name: 'return {;', regex: /return\s*\{\s*;/g },
        { name: 'return [;', regex: /return\s*\[\s*;/g },
        { name: '{;', regex: /\{\s*;/g },
        { name: '(;', regex: /\(\s*;/g },
        { name: '[;', regex: /\[\s*;/g },
        { name: ';)', regex: /;\s*\)/g },  // CRITICAL: semicolon before closing paren (if conditions!)
        { name: ';}', regex: /;\s*\}/g },
        { name: ';]', regex: /;\s*\]/g },
      ];

      criticalPatterns.forEach(pattern => {
        const matches = content.match(pattern.regex);
        if (matches && matches.length > 0) {
          this.logger.error('AICodeGenerator', `🚨 DETECTED SYNTAX ERROR IN AI RESPONSE: "${pattern.name}" found ${matches.length} time(s) in ${file.path}`, {
            pattern: pattern.name,
            occurrences: matches.length,
            file: file.path
          });
          console.error(`🚨 CRITICAL: Found "${pattern.name}" pattern ${matches.length} times in ${file.path}`);
        }
      });

      // 🔥 MULTI-PASS APPROACH: Run fixes iteratively until content stabilizes
      // This is CRITICAL because some patterns only appear after other fixes are applied
      // Example: "return {;\n  foo\n;}" needs 2 passes:
      //   Pass 1: Fix ";}" -> "}" resulting in "return {;\n  foo\n}"
      //   Pass 2: Fix "return {;" -> "return {" resulting in "return {\n  foo\n}"
      let previousContent = '';
      let passNumber = 0;
      const MAX_PASSES = 10; // Increased from 5 - AI generates MANY syntax errors

      while (previousContent !== content && passNumber < MAX_PASSES) {
        previousContent = content;
        passNumber++;

        if (passNumber > 1) {
          this.logger.info('AICodeGenerator', `🔄 Running syntax fix pass #${passNumber} for ${file.path}`);
          console.log(`🔄 Pass #${passNumber} for ${file.path}`);
        }

        // Fix 0a: CRITICAL - Remove "return (;" pattern
        content = content.replace(/return\s*\(\s*;+/g, (match) => {
          console.log(`🔧 [Pass ${passNumber}] Fixing return(; : "${match.replace(/\n/g, '\\n')}" -> "return ("`);
          this.logger.warning('AICodeGenerator', `[Pass ${passNumber}] Fixing return(;: "${match}" -> "return ("`, { file: file.path });
          fixesApplied++;
          return 'return (';
        });

        // Fix 0b: CRITICAL - Remove "return {;" pattern
        content = content.replace(/return\s*\{\s*;+/g, (match) => {
          console.log(`🔧 [Pass ${passNumber}] Fixing return{; : "${match.replace(/\n/g, '\\n')}" -> "return {"`);
          this.logger.warning('AICodeGenerator', `[Pass ${passNumber}] Fixing return{;: "${match}" -> "return {"`, { file: file.path });
          fixesApplied++;
          return 'return {';
        });

        // Fix 0c: CRITICAL - Remove "return [;" pattern
        content = content.replace(/return\s*\[\s*;+/g, (match) => {
          console.log(`🔧 [Pass ${passNumber}] Fixing return[; : "${match.replace(/\n/g, '\\n')}" -> "return ["`);
          this.logger.warning('AICodeGenerator', `[Pass ${passNumber}] Fixing return[;: "${match}" -> "return ["`, { file: file.path });
          fixesApplied++;
          return 'return [';
        });

        // Fix 0d: Remove ALL remaining stray semicolons after ANY opening delimiter
        // This catches cases not caught by the specific return fixes above
        // Fixes: (;  -> (   [;  -> [   {;  -> {
        // Match with whitespace including newlines to catch all cases
        content = content.replace(/([(\[{])\s*;+/g, (match, opener) => {
          console.log(`🔧 [Pass ${passNumber}] Fixing stray ; after opener: "${match.replace(/\n/g, '\\n')}" -> "${opener}"`);
          this.logger.warning('AICodeGenerator', `[Pass ${passNumber}] Fixing semicolon after delimiter: "${match}" -> "${opener}"`, { file: file.path });
          fixesApplied++;
          return opener;
        });

        // Fix 0e: Remove stray semicolons before closing delimiters
        // This is CRITICAL for if/while conditions: if (condition; ) should be if (condition )
        // Fixes: ;)  -> )   ;]  -> ]   ;}  -> }
        // Match semicolon followed by ANY whitespace (including newlines) followed by closing delimiter
        content = content.replace(/;+(\s*)([)\]}])/g, (match, whitespace, closer) => {
          console.log(`🔧 [Pass ${passNumber}] Fixing ; before closer: "${match.replace(/\n/g, '\\n')}" -> "${whitespace}${closer}"`);
          this.logger.warning('AICodeGenerator', `[Pass ${passNumber}] Fixing semicolon before delimiter: "${match.replace(/\n/g, '\\n')}" -> "${whitespace}${closer}"`, { file: file.path });
          fixesApplied++;
          return whitespace + closer; // Keep the whitespace, remove only the semicolon
        });

        // Fix 0f: Fix double semicolons
        content = content.replace(/;;+/g, () => {
          fixesApplied++;
          return ';';
        });
      }

      if (passNumber > 1) {
        this.logger.info('AICodeGenerator', `✅ Completed ${passNumber} syntax fix passes for ${file.path}`, {
          totalFixes: fixesApplied,
          file: file.path
        });
        console.log(`✅ Completed ${passNumber} passes with ${fixesApplied} total fixes for ${file.path}`);
      }

      // Fix 1: Add missing semicolons after return statements
      // Match: return (...); that is missing the semicolon
      const returnPattern = /(return\s*\([^)]*\)|return\s*<[^>]*>(?:[^<]|<[^/])*<\/[^>]*>|return\s+[^;\n]+)\s*$/gm;
      content = content.replace(returnPattern, (match) => {
        if (!match.trim().endsWith(';')) {
          fixesApplied++;
          return match.trim() + ';';
        }
        return match;
      });

      // Fix 2: Add missing semicolons after export statements
      // Match: export const/function/interface/type that is missing semicolon
      const exportPattern = /(export\s+(?:const|let|var|function|interface|type|enum)\s+[^;]+)\s*$/gm;
      content = content.replace(exportPattern, (match) => {
        if (!match.trim().endsWith(';') && !match.trim().endsWith('}')) {
          fixesApplied++;
          return match.trim() + ';';
        }
        return match;
      });

      // Fix 3: Add missing semicolons after arrow function declarations
      // Match: const foo = (...) => ... that is missing semicolon
      const arrowFuncPattern = /((?:const|let|var)\s+\w+\s*=\s*\([^)]*\)\s*=>\s*[^;{]+)\s*$/gm;
      content = content.replace(arrowFuncPattern, (match) => {
        if (!match.trim().endsWith(';') && !match.trim().endsWith('{')) {
          fixesApplied++;
          return match.trim() + ';';
        }
        return match;
      });

      // Fix 4: Add missing semicolons after multi-line function calls/expressions
      // This catches cases like: const x = useCallback(\n  ...\n) <- missing semicolon
      const lines = content.split('\n');
      const fixedLines = lines.map((line, index) => {
        const trimmed = line.trim();

        // Skip if already has semicolon, or ends with { or , or is a comment
        if (trimmed.endsWith(';') || trimmed.endsWith('{') || trimmed.endsWith(',') ||
            trimmed.startsWith('//') || trimmed.startsWith('/*') || !trimmed) {
          return line;
        }

        // Check for closing ) that might need semicolon
        if (trimmed === ')' || trimmed.endsWith(')')) {
          // Look back to find if this completes a const/let/var declaration
          let checkIndex = index - 1;
          let foundDeclaration = false;

          while (checkIndex >= 0 && index - checkIndex < 20) {
            const checkLine = lines[checkIndex].trim();
            if (checkLine.match(/^(const|let|var|export const|export let|export var)\s+\w+\s*=/)) {
              foundDeclaration = true;
              break;
            }
            // Stop if we hit another statement
            if (checkLine.includes(';') || checkLine.match(/^(function|class|interface|type|import)/)) {
              break;
            }
            checkIndex--;
          }

          if (foundDeclaration && !trimmed.endsWith(';')) {
            fixesApplied++;
            return line + ';';
          }
        }

        return line;
      });

      content = fixedLines.join('\n');

      if (fixesApplied > 0) {
        console.log(`🔧 Fixed ${fixesApplied} syntax issues in ${file.path}`);
      }

      // POST-FIX VERIFICATION: Check for critical syntax errors that should have been fixed
      const criticalErrors = this.verifySyntaxFixes(content, file.path);
      if (criticalErrors.length > 0) {
        console.error(`❌ CRITICAL: Syntax fixer failed to fix errors in ${file.path}:`);
        criticalErrors.forEach(error => console.error(`   - ${error}`));
        // Log the problematic content for debugging
        console.error(`Problematic content preview:\n${content.substring(0, 500)}...`);
      }

      return { ...file, content };
    });
  }

  /**
   * Validate extracted code for obvious truncation or corruption issues
   * Returns array of warning messages
   */
  private validateExtractedCode(content: string, filePath: string): string[] {
    const warnings: string[] = [];

    // Skip validation for non-code files
    if (!filePath.match(/\.(tsx?|jsx?)$/)) {
      return warnings;
    }

    // Check 1: Severe bracket/brace imbalance (indicates truncation)
    const openBraces = (content.match(/\{/g) || []).length;
    const closeBraces = (content.match(/\}/g) || []).length;
    const braceDiff = Math.abs(openBraces - closeBraces);
    if (braceDiff > 3) {
      warnings.push(`Severe brace mismatch: ${openBraces} open, ${closeBraces} close (diff: ${braceDiff})`);
    }

    // Check 2: File ends with opening delimiter (likely truncated)
    const lastChars = content.trim().slice(-10);
    if (/[({[][\s]*$/.test(lastChars)) {
      warnings.push(`File ends with opening delimiter - likely truncated`);
    }

    // Check 3: File has "return (" without matching close
    const returnMatches = content.match(/return\s*\(/g);
    if (returnMatches && returnMatches.length > 0) {
      const returnCount = returnMatches.length;
      // Count how many return statements have closing parens on same or next line
      const completeReturns = content.match(/return\s*\([^)]*\)|return\s*\(\s*\n/g);
      const completeCount = completeReturns ? completeReturns.length : 0;
      if (returnCount > completeCount + 2) {
        warnings.push(`Found ${returnCount} "return (" but only ${completeCount} appear complete`);
      }
    }

    return warnings;
  }

  /**
   * Verify that critical syntax errors have been fixed
   * Returns array of remaining error messages
   */
  private verifySyntaxFixes(content: string, filePath: string): string[] {
    const errors: string[] = [];

    // Check 1: return (; or return {; patterns
    if (/return\s*\(\s*;/.test(content)) {
      errors.push('Found "return (;" pattern - incomplete return statement');
    }
    if (/return\s*\{\s*;/.test(content)) {
      errors.push('Found "return {;" pattern - incomplete return statement');
    }

    // Check 2: Stray semicolons after opening delimiters
    if (/[(\[{]\s*;/.test(content)) {
      errors.push('Found stray semicolons after opening delimiters');
    }

    // Check 2b: CRITICAL - Semicolons BEFORE closing delimiters (if conditions!)
    if (/;\s*[)\]}]/.test(content)) {
      const matches = content.match(/;\s*[)\]}]/g);
      errors.push(`Found ${matches?.length || 0} semicolons before closing delimiters (e.g., "condition; )" in if statements)`);
    }

    // Check 3: Multiple semicolons
    if (/;;+/.test(content)) {
      errors.push('Found multiple consecutive semicolons');
    }

    // Check 4: Common incomplete statements
    if (/return\s*\(\s*$/.test(content)) {
      errors.push('Found incomplete return statement at end of line');
    }

    // Check 5: Unclosed JSX/parentheses (basic check)
    const openParens = (content.match(/\(/g) || []).length;
    const closeParens = (content.match(/\)/g) || []).length;
    if (Math.abs(openParens - closeParens) > 5) { // Allow some tolerance for string literals
      errors.push(`Parentheses mismatch: ${openParens} open, ${closeParens} close`);
    }

    return errors;
  }

  private stripLocalImports(code: string): string {
    const lines = code.split('\n');
    const filteredLines = lines.filter(line => {
      const trimmed = line.trim();
      // Remove lines with local imports
      if (trimmed.startsWith('import') && /from\s+['"]\.\.?\//.test(trimmed)) {
        return false;
      }
      return true;
    });
    return filteredLines.join('\n');
  }

  private extractDependenciesFromFiles(files: { path: string; content: string }[]): string[] {
    const allDeps = new Set<string>();

    files.forEach(file => {
      const deps = this.extractDependencies(file.content);
      deps.forEach(dep => allDeps.add(dep));
    });

    return Array.from(allDeps);
  }

  private extractDependencies(code: string): string[] {
    const dependencies: string[] = [];

    // Common dependencies to check for
    const dependencyMap: Record<string, string> = {
      'useState': 'react',
      'useEffect': 'react',
      'useCallback': 'react',
      'useMemo': 'react',
      'useRef': 'react',
      'framer-motion': 'framer-motion',
      'react-router': 'react-router-dom',
      'axios': 'axios',
      'date-fns': 'date-fns',
      'lodash': 'lodash',
      'uuid': 'uuid',
      'react-hook-form': 'react-hook-form',
      'zod': 'zod',
      'recharts': 'recharts',
      'lucide-react': 'lucide-react',
      'clsx': 'clsx',
      'tailwind-merge': 'tailwind-merge',
    };

    // Check for imports and usage
    for (const [importName, packageName] of Object.entries(dependencyMap)) {
      if (code.includes(importName) && !dependencies.includes(packageName)) {
        dependencies.push(packageName);
      }
    }

    // Always include React dependencies
    if (!dependencies.includes('react')) {
      dependencies.push('react');
    }
    if (!dependencies.includes('react-dom')) {
      dependencies.push('react-dom');
    }

    return dependencies;
  }

  private ensureRequiredFiles(
    files: { path: string; content: string }[],
    dependencies: string[],
    componentName: string
  ): { path: string; content: string }[] {
    const result = [...files];
    const existingPaths = new Set(files.map(f => f.path));

    // Required devDependencies that MUST be present for the app to build
    const requiredDevDeps = {
      '@types/react': '^18.3.18',
      '@types/react-dom': '^18.3.5',
      '@vitejs/plugin-react': '^5.0.0',
      'autoprefixer': '^10.4.20',
      'postcss': '^8.4.47',
      'tailwindcss': '^3.4.14',
      'typescript': '^5.7.2',
      'vite': '^7.1.7'
    };

    // Ensure package.json with proper dependencies
    const existingPackageJsonIndex = result.findIndex(f => f.path === 'package.json');

    if (existingPackageJsonIndex === -1) {
      // No package.json exists - create one
      const depObj: Record<string, string> = {
        'react': '^18.3.1',
        'react-dom': '^18.3.1',
      };

      // Add detected dependencies
      dependencies.forEach(dep => {
        if (dep === 'framer-motion') depObj[dep] = '^11.13.1';
        else if (dep === 'lucide-react') depObj[dep] = '^0.453.0';
        else if (dep === 'clsx') depObj[dep] = '^2.1.1';
        else if (dep === 'tailwind-merge') depObj[dep] = '^2.5.4';
        else if (dep === 'date-fns') depObj[dep] = '^3.6.0';
        else if (dep === 'recharts') depObj[dep] = '^2.13.0';
        else if (dep === 'react-hook-form') depObj[dep] = '^7.53.1';
        else if (dep === 'zod') depObj[dep] = '^3.25.76';
        else if (dep === 'react-router-dom') depObj[dep] = '^6.26.0';
        else if (!depObj[dep]) depObj[dep] = 'latest';
      });

      result.push({
        path: 'package.json',
        content: JSON.stringify({
          name: componentName.toLowerCase().replace(/\s+/g, '-'),
          version: '0.1.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview'
          },
          dependencies: depObj,
          devDependencies: requiredDevDeps
        }, null, 2)
      });
    } else {
      // package.json exists - merge required devDependencies
      try {
        const existingPackageJson = JSON.parse(result[existingPackageJsonIndex].content);

        // Ensure devDependencies object exists
        if (!existingPackageJson.devDependencies) {
          existingPackageJson.devDependencies = {};
        }

        // Merge required devDependencies (our versions take precedence to ensure compatibility)
        Object.assign(existingPackageJson.devDependencies, requiredDevDeps);

        // Ensure dependencies object exists with at least react and react-dom
        if (!existingPackageJson.dependencies) {
          existingPackageJson.dependencies = {};
        }
        if (!existingPackageJson.dependencies.react) {
          existingPackageJson.dependencies.react = '^18.3.1';
        }
        if (!existingPackageJson.dependencies['react-dom']) {
          existingPackageJson.dependencies['react-dom'] = '^18.3.1';
        }

        // Ensure scripts exist
        if (!existingPackageJson.scripts) {
          existingPackageJson.scripts = {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview'
          };
        }

        // Ensure type module is set
        existingPackageJson.type = 'module';

        // Update the package.json in the result
        result[existingPackageJsonIndex].content = JSON.stringify(existingPackageJson, null, 2);

        this.logger.info('AICodeGenerator', 'Merged required devDependencies into AI-generated package.json', {
          addedDeps: Object.keys(requiredDevDeps)
        });
      } catch (error) {
        this.logger.error('AICodeGenerator', 'Failed to parse existing package.json, replacing it', { error });
        // If parsing fails, replace with our own
        const depObj: Record<string, string> = {
          'react': '^18.3.1',
          'react-dom': '^18.3.1',
        };
        dependencies.forEach(dep => {
          if (dep === 'framer-motion') depObj[dep] = '^11.13.1';
          else if (dep === 'lucide-react') depObj[dep] = '^0.453.0';
          else if (dep === 'clsx') depObj[dep] = '^2.1.1';
          else if (dep === 'tailwind-merge') depObj[dep] = '^2.5.4';
          else if (dep === 'date-fns') depObj[dep] = '^3.6.0';
          else if (dep === 'recharts') depObj[dep] = '^2.13.0';
          else if (dep === 'react-hook-form') depObj[dep] = '^7.53.1';
          else if (dep === 'zod') depObj[dep] = '^3.25.76';
          else if (dep === 'react-router-dom') depObj[dep] = '^6.26.0';
          else if (!depObj[dep]) depObj[dep] = 'latest';
        });

        result[existingPackageJsonIndex].content = JSON.stringify({
          name: componentName.toLowerCase().replace(/\s+/g, '-'),
          version: '0.1.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview'
          },
          dependencies: depObj,
          devDependencies: requiredDevDeps
        }, null, 2);
      }
    }

    // Ensure index.html
    if (!existingPaths.has('index.html')) {
      result.push({
        path: 'index.html',
        content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${componentName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`
      });
    }

    // Ensure vite.config.ts
    if (!existingPaths.has('vite.config.ts')) {
      result.push({
        path: 'vite.config.ts',
        content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    open: true
  }
});`
      });
    }

    // Ensure tsconfig.json
    if (!existingPaths.has('tsconfig.json')) {
      result.push({
        path: 'tsconfig.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2020',
            useDefineForClassFields: true,
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowImportingTsExtensions: true,
            isolatedModules: true,
            moduleDetection: 'force',
            noEmit: true,
            jsx: 'react-jsx',
            strict: true,
            noUnusedLocals: true,
            noUnusedParameters: true,
            noFallthroughCasesInSwitch: true,
            noUncheckedSideEffectImports: true
          },
          include: ['src']
        }, null, 2)
      });
    }

    // Ensure tsconfig.node.json (required by vite.config.ts)
    if (!existingPaths.has('tsconfig.node.json')) {
      result.push({
        path: 'tsconfig.node.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2022',
            lib: ['ES2023'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'bundler',
            allowSyntheticDefaultImports: true,
            strict: true,
            resolveJsonModule: true,
            isolatedModules: true,
            moduleDetection: 'force',
            noEmit: true
          },
          include: ['vite.config.ts']
        }, null, 2)
      });
    }

    // Ensure tailwind.config.js
    if (!existingPaths.has('tailwind.config.js')) {
      result.push({
        path: 'tailwind.config.js',
        content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
      });
    }

    // Ensure postcss.config.js
    if (!existingPaths.has('postcss.config.js')) {
      result.push({
        path: 'postcss.config.js',
        content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
      });
    }

    // Ensure src/main.tsx if not present
    if (!existingPaths.has('src/main.tsx')) {
      result.push({
        path: 'src/main.tsx',
        content: `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);`
      });
    }

    // Ensure src/index.css if not present
    if (!existingPaths.has('src/index.css')) {
      result.push({
        path: 'src/index.css',
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}`
      });
    }

    // 🚨 CRITICAL: Ensure src/App.tsx ALWAYS exists (main.tsx imports it)
    if (!existingPaths.has('src/App.tsx')) {
      this.logger.warning('AICodeGenerator', 'AI did not generate src/App.tsx - creating fallback', {
        componentName
      });

      result.push({
        path: 'src/App.tsx',
        content: `// Main application component
export default function App() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
      <div className="max-w-2xl w-full bg-white rounded-2xl shadow-xl p-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          ${componentName}
        </h1>
        <p className="text-lg text-gray-600 mb-6">
          Welcome to your new application! This is a starter template.
        </p>
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <p className="text-sm text-blue-800">
            💡 <strong>Next steps:</strong> Customize this component to build your application.
          </p>
        </div>
      </div>
    </div>
  );
}`
      });
      existingPaths.add('src/App.tsx');
    }

    this.logger.info('AICodeGenerator', `Ensured all required files. Total files: ${result.length}`, {
      addedFiles: result.length - files.length
    });

    return result;
  }

  /**
   * Validates all imports in generated files and creates missing files
   * This fixes the issue where AI generates imports but not the actual files
   */
  private validateAndFixImports(files: { path: string; content: string }[]): { path: string; content: string }[] {
    const result = [...files];
    const existingPaths = new Set(files.map(f => f.path));
    const missingFiles = new Map<string, string[]>(); // path -> [files that import it]

    // Extract all imports from all files
    for (const file of files) {
      const imports = this.extractLocalImports(file.content);

      for (const importPath of imports) {
        // Convert relative import to absolute path
        const absolutePath = this.resolveImportPath(file.path, importPath);

        if (absolutePath && !existingPaths.has(absolutePath)) {
          if (!missingFiles.has(absolutePath)) {
            missingFiles.set(absolutePath, []);
          }
          missingFiles.get(absolutePath)!.push(file.path);
        }
      }
    }

    // Create stub files for missing imports
    if (missingFiles.size > 0) {
      this.logger.warning('AICodeGenerator', `Found ${missingFiles.size} missing imported files, creating stubs`, {
        missingFiles: Array.from(missingFiles.keys())
      });

      for (const [missingPath, importers] of missingFiles.entries()) {
        const stubContent = this.createStubFile(missingPath, importers);
        result.push({
          path: missingPath,
          content: stubContent
        });
        existingPaths.add(missingPath);
      }
    }

    return result;
  }

  /**
   * Extract local import paths from TypeScript/JavaScript code
   */
  private extractLocalImports(content: string): string[] {
    const imports: string[] = [];

    // Match: import ... from './path' or import ... from '../path'
    const importRegex = /import\s+(?:{[^}]+}|[^'\s]+|\*\s+as\s+[^\s]+)\s+from\s+['"](\.\/.+?|\.\.?\/.+?)['"];?/g;

    let match;
    while ((match = importRegex.exec(content)) !== null) {
      imports.push(match[1]);
    }

    return imports;
  }

  /**
   * Resolve relative import path to absolute file path
   */
  private resolveImportPath(fromFile: string, importPath: string): string | null {
    // Get directory of the importing file
    const fromDir = fromFile.substring(0, fromFile.lastIndexOf('/'));

    // Handle different import patterns
    let targetPath = importPath;

    // Remove leading './' or '../'
    const parts = importPath.split('/');
    let currentDir = fromDir;

    for (const part of parts) {
      if (part === '..') {
        // Go up one directory
        const lastSlash = currentDir.lastIndexOf('/');
        currentDir = lastSlash > 0 ? currentDir.substring(0, lastSlash) : '';
      } else if (part === '.') {
        // Stay in current directory
        continue;
      } else {
        // Add to path
        currentDir = currentDir ? `${currentDir}/${part}` : part;
      }
    }

    // Check if path already has a valid extension
    if (currentDir.match(/\.(tsx?|jsx?|js|css|json)$/)) {
      return currentDir;
    }

    // Try adding extensions
    const possibleExtensions = ['.tsx', '.ts', '.jsx', '.js', '/index.tsx', '/index.ts'];

    for (const ext of possibleExtensions) {
      const testPath = currentDir + ext;
      if (!testPath.includes('..')) {
        return testPath;
      }
    }

    // If no extension and no index, default to .tsx
    return currentDir + '.tsx';
  }

  /**
   * Create a stub file for a missing import
   */
  private createStubFile(path: string, importedBy: string[]): string {
    const fileName = path.substring(path.lastIndexOf('/') + 1).replace(/\.(tsx?|jsx?)$/, '');
    const isComponent = path.includes('/components/') || fileName.charAt(0) === fileName.charAt(0).toUpperCase();
    const isType = path.includes('/types/') || path.endsWith('types.ts');
    const isHook = path.includes('/hooks/') || fileName.startsWith('use');
    const isUtil = path.includes('/utils/') || path.includes('/lib/');
    const isContext = path.includes('/context/');

    if (isType) {
      // Create type definition file
      return `// Type definitions
// Auto-generated stub - imported by: ${importedBy.join(', ')}

export interface ${fileName.replace(/[-_]/g, '')} {
  id: string | number;
  [key: string]: any;
}

export type ${fileName}Type = ${fileName.replace(/[-_]/g, '')};
`;
    }

    if (isContext) {
      // Create context file (React 18+ JSX transform)
      return `import { createContext, useContext, ReactNode } from 'react';

// Auto-generated stub - imported by: ${importedBy.join(', ')}

interface ${fileName}ContextType {
  // Add your context properties here
  value: any;
}

const ${fileName}Context = createContext<${fileName}ContextType | undefined>(undefined);

export function ${fileName}Provider({ children }: { children: ReactNode }) {
  const value = {
    value: null
  };

  return (
    <${fileName}Context.Provider value={value}>
      {children}
    </${fileName}Context.Provider>
  );
}

export function use${fileName}() {
  const context = useContext(${fileName}Context);
  if (context === undefined) {
    throw new Error('use${fileName} must be used within a ${fileName}Provider');
  }
  return context;
}
`;
    }

    if (isHook) {
      // Create custom hook file
      return `import { useState } from 'react';

// Auto-generated stub - imported by: ${importedBy.join(', ')}

export const ${fileName} = () => {
  const [state, setState] = useState<any>(null);

  return {
    state,
    setState
  };
};
`;
    }

    if (isUtil) {
      // Create utility file
      return `// Utility functions
// Auto-generated stub - imported by: ${importedBy.join(', ')}

export const ${fileName.replace(/[-_]/g, '')} = (input: any): any => {
  return input;
};

export default ${fileName.replace(/[-_]/g, '')};
`;
    }

    if (isComponent) {
      // Create React component file (React 18+ JSX transform - no React import needed)
      return `// Auto-generated stub - imported by: ${importedBy.join(', ')}

interface ${fileName}Props {
  [key: string]: any;
}

export function ${fileName}(props: ${fileName}Props) {
  return (
    <div className="p-4">
      <h2 className="text-xl font-semibold">${fileName}</h2>
      <p className="text-gray-600">This component is under development.</p>
    </div>
  );
}

export default ${fileName};
`;
    }

    // Default: Create a simple module
    return `// Auto-generated module
// Imported by: ${importedBy.join(', ')}

export const placeholder = true;

export default {};
`;
  }

  async generateHooks(componentName: string, features: string[]): Promise<string> {
    try {
      const systemPrompt = `You are an expert React developer. Generate custom hooks for a React component.

Create TypeScript custom hooks that would be useful for a "${componentName}" component with these features: ${features.join(', ')}.

Return ONLY the hook code, no explanations.`;

      const userPrompt = `Generate useful custom hooks for the ${componentName} component. Focus on hooks that would be commonly used with these features: ${features.join(', ')}.`;

      const response = await this.anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 2000,
        temperature: 0.7,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      });

      return response.content[0]?.type === 'text' ? response.content[0].text : '';
    } catch (error) {
      this.logger.error('AICodeGenerator', 'Failed to generate hooks', { error });
      return '';
    }
  }

  async generateTypes(componentName: string, features: string[]): Promise<string> {
    try {
      const systemPrompt = `You are an expert TypeScript developer. Generate TypeScript type definitions for a React component.

Create comprehensive TypeScript interfaces and types for a "${componentName}" component with these features: ${features.join(', ')}.

Return ONLY the TypeScript type definitions, no explanations.`;

      const userPrompt = `Generate TypeScript types and interfaces for the ${componentName} component. Include all necessary types for the features: ${features.join(', ')}.`;

      const response = await this.anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 1500,
        temperature: 0.7,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      });

      return response.content[0]?.type === 'text' ? response.content[0].text : '';
    } catch (error) {
      this.logger.error('AICodeGenerator', 'Failed to generate types', { error });
      return '';
    }
  }

}

// Export singleton instance
export const aiCodeGenerator = new AICodeGenerator();
